import {useEffect,useState} from 'react';
import {ArrowRight,CalendarBlank,CalendarCheck,CalendarPlus,CaretLeft,CaretRight,Flag,Path,Shuffle,X} from '@phosphor-icons/react';
import {KeyboardInput,useFlow,useKeyboard,BottomSheet} from './mobile';
import {CarrierBadge,PageBody,screen,useApp} from './Prototype';
import {addPersonalFlight,airports,date,duration,routeDistance,type Flight} from './domain';
import {carriers,demoDate,localTime,parseDepartureDate,parseFlightNumber,sampleSearch,shortDate} from './flightCatalog';

function countdown(f:Flight){const remaining=Math.floor((Date.parse(f.departure)-(f.source==='live'?Date.now():Date.parse('2026-09-15T04:56:00Z')))/60000);return remaining<0?['Past','FLIGHT']:remaining>=1440?[String(Math.floor(remaining/1440)),'DAYS']:[`${Math.floor(remaining/60)}h`,`${remaining%60} MINUTES`];}

type Step='query'|'route'|'date'|'results'|'manual';
export default function AddFlight(){
 const app=useApp(),flow=useFlow(),keyboard=useKeyboard();
 const [step,setStep]=useState<Step>('query'),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[day,setDay]=useState(''),[results,setResults]=useState<Flight[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[live,setLive]=useState(false),[calendar,setCalendar]=useState(false),[month,setMonth]=useState(8),[year,setYear]=useState(2026),[minutes,setMinutes]=useState(''),[calendarInfo,setCalendarInfo]=useState(false);
 const parsed=parseFlightNumber(query),queryText=query.trim().toLowerCase();
 useEffect(()=>{if(!['localhost','127.0.0.1'].includes(location.hostname))return;const controller=new AbortController();fetch('http://127.0.0.1:4175/status',{signal:controller.signal}).then(r=>r.json()).then(r=>setLive(r.configured===true)).catch(()=>{});return()=>controller.abort();},[]);
 const change=(next:Step)=>{keyboard.hide();setError('');setStep(next);};
 const search=async(value:string,overrideNumber?:string)=>{const selected=parseDepartureDate(value);if(!selected){setError('Enter a valid date, like 10/5, Friday, or 2026-09-15.');return;}keyboard.hide();setDay(selected);setCalendar(false);setStep('results');setLoading(true);setError('');try{if(live){const params=new URLSearchParams({date:selected,...(overrideNumber?{number:overrideNumber}:parsed?{number:parsed.carrier.code+parsed.number}:{from,to})});const r=await fetch(`http://127.0.0.1:4175/flights?${params}`);const data=await r.json();if(!r.ok)throw Error(data.error??'Flight lookup failed.');setResults(data.flights);if(data.omitted)setError(`${data.omitted} results use airports not yet supported by this demo.`);}else setResults(sampleSearch(selected,overrideNumber??(parsed?parsed.carrier.code+parsed.number:''),from,to));}catch(e){setResults([]);setError((e as Error).message);}finally{setLoading(false);}};
 const added=(f:Flight)=>app.records.some(r=>r.number.replace(/\s/g,'')===f.number.replace(/\s/g,'')&&r.from===f.from&&r.to===f.to&&date(r,true)===date(f,true));
 const add=(f:Flight)=>{try{app.save(addPersonalFlight(app.state,f),'Added to My Flights');}catch(e){setError((e as Error).message);}};
 const manual=()=>{const selected=parseDepartureDate(day);if(!parsed||!selected){setError('Enter a recognized airline and flight number, and a valid departure date.');return;}if(minutes&&(!/^\d+$/.test(minutes)||Number(minutes)>3000||Number(minutes)<1)){setError('Flight duration must be between 1 and 3,000 minutes, or left empty.');return;}const airport=airports[from];if(!airport||!airports[to]||from===to){setError('Choose two different supported airports.');return;}const f:Flight={id:`manual-${Date.now()}`,number:`${parsed.carrier.code} ${parsed.number}`,carrier:parsed.carrier.name,from,to,departure:`${selected}T12:00:00Z`,arrival:'',dateOnly:true,minutes:minutes?Number(minutes):null,km:routeDistance(from,to),distanceEstimated:true,source:'manual',status:selected<demoDate?'flown':'planned'};try{const next=addPersonalFlight(app.state,f);if(app.save(next,'Flight added')){keyboard.hide();flow.replace(screen('home'));}}catch(e){setError((e as Error).message);}};
 const routeReady=()=>{if(!airports[from]||!airports[to]||from===to){setError('Enter two different airport codes from the supported airport list.');return;}setQuery('');change('date');};
 const subtitle=step==='query'?'Enter airline, airport, or flight':step==='date'?'Enter departure date':step==='results'?'Tap flight to add to My Flights':step==='manual'?'Enter the details you know':'Find a flight by route';
 const close=()=>{keyboard.hide();flow.canGoBack?flow.pop():flow.replace(screen('home'));};
 return <div className="add-flight-shell"><PageBody><div className="add-flight-content"><div className="add-flight-heading"><h1>Add Flight</h1><button className="header-circle" aria-label="Close Add Flight" onClick={close}><X size={28}/></button></div><p className="add-subtitle">{subtitle}</p>
 {step==='query'&&<><div className="flight-search-input"><KeyboardInput aria-label="Search flight records" placeholder="United, PIT, or UA123" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&parsed)change('date');}} autoComplete="off"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={18}/></button>}</div>
 {parsed?<button className="lookup-row" onClick={()=>change('date')}><CarrierBadge carrier={parsed.carrier.name}/><span><strong>{parsed.carrier.name} {parsed.number}</strong><small>Detected flight number</small></span><ArrowRight/></button>:<><p className="lookup-label">{query?'MATCHES':'FREQUENTLY USED'}</p>{carriers.filter(c=>!query?['UA','WN'].includes(c.code):`${c.name} ${c.code} ${c.icao}`.toLowerCase().includes(queryText)).map(c=><button key={c.code} className="lookup-row" onClick={()=>{setQuery(c.code);setError('Enter the flight number after '+c.code);}}><CarrierBadge carrier={c.name}/><span><strong>{c.name}</strong><small>{c.code} · {c.icao}</small></span><ArrowRight/></button>)}{Object.values(airports).filter(a=>!query?['PIT','SFO'].includes(a.code):`${a.code} ${a.city} ${a.name}`.toLowerCase().includes(queryText)).map(a=><button className="lookup-row" key={a.code} onClick={()=>{setFrom(a.code);setTo('');change('route');}}><img className="airport-flag" src={`/assets/flags/${a.country??'us'}.png`} alt=""/><span><strong>{a.name}</strong><small>{a.code} · {a.city}</small></span></button>)}</>}
 <p className="lookup-label">MORE</p><button className="lookup-row" onClick={()=>change('route')}><Path/><strong>Find by Route</strong></button><button className="lookup-row" onClick={()=>{setQuery('UA');setError('Enter an airline code and flight number, like UA123.');}}><CalendarBlank/><strong>Find by Flight Number</strong></button><button className="lookup-row" onClick={()=>setCalendarInfo(true)}><CalendarCheck/><span><strong>Sync from Calendar</strong><small>Calendar connection options</small></span></button><button className="lookup-row" onClick={()=>{setQuery('UA123');void search(demoDate,'UA123');}}><Shuffle/><span><strong>Random Flight</strong><small>Explore a sample flight</small></span></button><button className="lookup-row" onClick={()=>change('manual')}><Flag/><strong>Add Manually</strong></button></>}
 {(step==='date'||step==='results')&&<><div className="flight-entry-segments"><button onClick={()=>change(parsed?'query':'route')}>{parsed?.carrier.code??from}</button><button onClick={()=>change(parsed?'query':'route')}>{parsed?.number??to}</button>{step==='date'?<KeyboardInput aria-label="Departure date" placeholder="10/5 or Friday" value={day} onChange={e=>setDay(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search(day)}/>:<button className="date-segment" onClick={()=>change('date')}>{shortDate(day)}</button>}</div>{step==='date'&&<><button className="lookup-row" onClick={()=>search(demoDate)}><CalendarCheck/><span><strong>Today</strong><small>{shortDate(demoDate)}</small></span><ArrowRight/></button><button className="lookup-row" onClick={()=>search('tomorrow')}><CalendarPlus/><span><strong>Tomorrow</strong><small>{shortDate('2026-09-16')}</small></span></button><button className="lookup-row" onClick={()=>{keyboard.hide();setCalendar(true);}}><CalendarBlank/><strong>Pick from Calendar</strong></button>{day&&<button className="primary" onClick={()=>search(day)}>Find flights</button>}</>}</>}
 {step==='route'&&<><div className="route-fields"><label>From<KeyboardInput aria-label="Departure airport" placeholder="PIT" value={from} onChange={e=>setFrom(e.target.value.toUpperCase())}/></label><ArrowRight/><label>To<KeyboardInput aria-label="Arrival airport" placeholder="ORD" value={to} onChange={e=>setTo(e.target.value.toUpperCase())}/></label></div><p className="fineprint">{Object.values(airports).map(a=>`${a.code} (${a.city})`).join(' · ')}</p><button className="primary" onClick={routeReady}>Choose date<ArrowRight/></button></>}
 {step==='results'&&<><p className="lookup-source">{live?'Online flight data':'Sample flight results · demo schedule'}</p>{loading?<p role="status">Finding flights…</p>:results.map(f=><button className="flight-search-result" key={f.id} onClick={()=>add(f)} disabled={added(f)}><span className="result-duration"><strong>{countdown(f)[0]}</strong><small>{countdown(f)[1]}</small></span><span className="result-main"><span className="section-heading"><span><CarrierBadge carrier={f.carrier}/>{f.number}</span><span className={added(f)?'added-label':''}>{added(f)?'Added ✓':f.source==='live'?'Scheduled':'Sample'}</span></span><strong>{airports[f.from].city} to {airports[f.to].city}</strong><span className="result-times">↗ {f.from} <b>{localTime(f.departure,f.from)}</b>　↘ {f.to} <b>{localTime(f.arrival,f.to)}</b></span></span></button>)}{!loading&&!results.length&&!error&&<p className="empty-result">No {live?'matching':'sample'} flights for this search. Add the flight manually using your itinerary.</p>}<div className="missing-flight"><span>Flight missing?</span><button onClick={()=>{if(results[0]){setFrom(results[0].from);setTo(results[0].to);}change('manual');}}><Flag/>Add Manually</button></div>{results.some(added)&&<button className="primary" onClick={()=>flow.replace(screen('home'))}>View My Flights</button>}</>}
 {step==='manual'&&<div className="manual-fields"><label className="field">Flight number<KeyboardInput aria-label="Manual flight number" placeholder="UA123" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="route-fields"><label>From<KeyboardInput aria-label="Manual departure airport" value={from} placeholder="LHR" onChange={e=>setFrom(e.target.value.toUpperCase())}/></label><label>To<KeyboardInput aria-label="Manual arrival airport" value={to} placeholder="EWR" onChange={e=>setTo(e.target.value.toUpperCase())}/></label></div><p className="fineprint">Supported airports: {Object.keys(airports).join(', ')}</p><label className="field">Departure date<KeyboardInput aria-label="Manual departure date" value={day} placeholder="2026-09-15" onChange={e=>setDay(e.target.value)}/></label><label className="field">Flight time in minutes (optional)<KeyboardInput aria-label="Manual duration" value={minutes} inputMode="numeric" placeholder="e.g. 458" onChange={e=>setMinutes(e.target.value)}/></label><p className="fineprint">The date is recorded as entered. Exact departure/arrival times and delays remain unknown. Distance is estimated between the airports.</p><button className="primary" onClick={manual}>Add to My Flights</button></div>}
 {error&&<p className="form-message" role="status">{error}</p>}{step!=='query'&&<button className="text-button" onClick={()=>change('query')}><CaretLeft size={16}/>Back to search</button>}</div></PageBody>
 <BottomSheet open={calendar} onOpenChange={setCalendar} title="Departure date" snap={.65}><div className="calendar-heading"><button aria-label="Previous month" onClick={()=>{if(month===0){setMonth(11);setYear(year-1);}else setMonth(month-1);}}><CaretLeft/></button><strong>{new Date(year,month).toLocaleString('en',{month:'long'})} {year}</strong><button aria-label="Next month" onClick={()=>{if(month===11){setMonth(0);setYear(year+1);}else setMonth(month+1);}}><CaretRight/></button></div><div className="calendar-grid">{['S','M','T','W','T','F','S'].map((s,i)=><span key={i}>{s}</span>)}{Array.from({length:new Date(year,month,1).getDay()},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:new Date(year,month+1,0).getDate()},(_,i)=><button key={i} aria-label={`Select ${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`} onClick={()=>search(`${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`)}>{i+1}</button>)}</div></BottomSheet>
 <BottomSheet open={calendarInfo} onOpenChange={setCalendarInfo} title="Sync from Calendar" description="Calendar permissions are not connected in this browser prototype." snap={.4}><p>You can add a flight from your itinerary using its flight number and date.</p><button className="primary" onClick={()=>{setCalendarInfo(false);change('manual');}}>Add a flight manually</button><button className="text-button" onClick={()=>setCalendarInfo(false)}>Done</button></BottomSheet></div>;
}
