import {useState} from 'react';
import {AirplaneTilt,ArrowUpRight,ArrowDownRight,Armchair,CaretRight,Clock,Copy,DotsThree,Export,Flag,GlobeSimple,NotePencil,SunHorizon,Ticket,WarningCircle,X} from '@phosphor-icons/react';
import {BottomSheet,KeyboardInput,KeyboardTextarea,useFlow,useKeyboard} from './mobile';
import {CarrierBadge,MapPanel,PageBody,screen,useApp} from './Prototype';
import {aircraftNames,airports,date,duration,flightMetadata,historyMatch,routeHistory,totals,type Flight} from './domain';
import {friendFlights,localTime} from './flightCatalog';
import {cx882Facts} from './flightFacts';

type Sheet='edit'|'share'|'more'|'report'|'connection'|'aircraft'|null;
export default function FlightInformation({id}:{id:string}){
 const app=useApp(),flow=useFlow(),keyboard=useKeyboard(),f=app.records.find(r=>r.id===id)??friendFlights.find(r=>r.id===id);
 const [sheet,setSheet]=useState<Sheet>(null),[note,setNote]=useState(app.state.flightNotes?.[id]??''),[booking,setBooking]=useState(app.state.flightFields?.[id]?.booking??''),[seat,setSeat]=useState(app.state.flightFields?.[id]?.seat??f?.seat??''),[report,setReport]=useState('');
 const closeSheet=()=>{keyboard.hide();setSheet(null);};
 if(!f)return <PageBody><p>Flight unavailable.</p></PageBody>;
 const facts=id==='ref23-cx882'?cx882Facts:null,meta=flightMetadata(f),knownDelay=meta.delay,status=f.status==='canceled'?'Canceled':f.status==='planned'?'Upcoming flight':knownDelay===null?'Flight completed':knownDelay>0?`Arrived ${knownDelay}m Late`:'Arrived On Time';
 const history=routeHistory(f,app.state.empty?[]:app.records),stats=totals(history),samePlane=app.records.filter(r=>r.status==='flown'&&f.registration&&r.registration===f.registration);
 const close=()=>flow.canGoBack?flow.pop():flow.replace(screen('overview'));
 const save=()=>{if(app.save({...app.state,flightNotes:{...app.state.flightNotes,[id]:note},flightFields:{...app.state.flightFields,[id]:{booking,seat}}},'Flight details saved on this device'))closeSheet();};
 const heading=<div className="flight-sheet-heading"><CarrierBadge carrier={f.carrier}/><div><p>{f.number} · {new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric',timeZone:airports[f.from].zone}).format(new Date(f.departure)).toUpperCase()}</p><h1>{airports[f.from].city} to {airports[f.to].city}</h1></div><button className="header-circle" aria-label="Close flight details" onClick={close}><X size={28}/></button></div>;
 const summary=`${f.number} · ${date(f,true)}\n${airports[f.from].city} to ${airports[f.to].city}\n${duration(f.minutes)} · ${f.distanceEstimated?'Estimated ':''}${f.km.toLocaleString()} km\n${status}`;
 const download=(text:string,name:string)=>{const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <><MapPanel page="flight" flight={f} heading={heading}><PageBody><div className="flight-information">
 <div className={`arrival-banner ${knownDelay&&knownDelay>0?'late-banner':''}`}><strong>{status}</strong><p>Total {duration(f.minutes)} · {f.distanceEstimated?'≈ ':''}{f.km.toLocaleString()} km</p></div>
 <div className="flight-info-body">
 <AirportTime flight={f} departure scheduled={facts?.scheduledDeparture} delay={facts?.departureDelay} terminal={facts?.departureTerminal}/>
 <div className="flight-duration-line"><Clock size={15}/>{duration(f.minutes)} · {f.distanceEstimated?'≈ ':''}{f.km.toLocaleString()} km<span/></div>
 <AirportTime flight={f} scheduled={facts?.scheduledArrival} delay={knownDelay??undefined} terminal={facts?.arrivalTerminal}/>
 <div className="flight-personal-fields"><button onClick={()=>setSheet('edit')}><Ticket size={24}/><strong>Booking Code</strong><span>{app.state.flightFields?.[id]?.booking||'Tap to Edit'}</span></button><button onClick={()=>setSheet('edit')}><Armchair size={25}/><strong>Seat</strong><span>{app.state.flightFields?.[id]?.seat||f.seat||'Tap to Edit'}</span></button></div>
 {id==='next'&&historyMatch(app.state,f,app.now)&&<button className="history-cue" onClick={()=>flow.push(screen('history'))}><Clock/><span>You’ve flown this route<small>Read your previous trip note</small></span><CaretRight/></button>}
 {facts&&<><h2 className="flight-section-title">Good to Know</h2><div className="flight-info-card compact-info"><SunHorizon size={26} color="#ffbf00"/><div><strong>Arrival Weather</strong><p>25°C and few clouds</p></div></div><button className="flight-info-card compact-info" onClick={()=>setSheet('connection')}><AirplaneTilt size={26}/><div><strong>Relaxed Connection</strong><p>5h 15m between flights at HKG. That’s 4h 25m more than the suggested minimum.</p></div><CaretRight size={20}/></button><div className="flight-info-card compact-info"><GlobeSimple size={26}/><div><strong>−15 Hours Timezone Change</strong><p>Arrival is 6:13 AM in Hong Kong the next day.</p></div></div>
 <section className="flight-info-card forecast-card"><h2>Arrival Forecast</h2><p>CX 882 performance over the last 60 days</p><div className="forecast-totals"><div><small>Late</small><strong>48%</strong></div><div><small>Average of Late</small><strong>37m</strong></div><div><small>Observed</small><strong>25</strong></div></div>{facts.forecast.rows.map(([label,percent,color])=><div className="forecast-row" key={label}><span>{label}</span><div role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><span style={{width:`${percent}%`,background:color}}/></div><span>{percent}%</span></div>)}<small className="flight-provenance">Historical snapshot from your reference, not a current forecast.</small></section>
 <section className="flight-info-card plane-info"><h2>Where’s My Plane?</h2><p>Boeing 777-300 ER · B-KPX</p><small>First Flight: Aug 15, 2011 · 12 years old at this flight</small><img src="/assets/aircraft/b777-stars.png" alt="Boeing 777-300 ER in a starry sky"/><p>Plane was already at the airport or did not fly known flights in the 25-hour prior to this flight.</p><button className="plane-history-link" onClick={()=>setSheet('aircraft')}><AirplaneTilt size={28}/><span>You have {samePlane.length} flights on this aircraft</span><CaretRight/></button></section>
 <section className="flight-info-card timetable"><h2>Detailed Timetable</h2><p>Scheduled, Estimated, Predicted, and Actual</p>{facts.timetable.map(group=><div className="timetable-group" key={group.group}><p>{group.group}</p>{group.rows.map(([label,scheduled,actual,color])=><div className="timetable-row" key={label}><span>{label}</span><div><small>Scheduled</small>{scheduled}</div><div className={color}><small>Actual</small>{actual}</div></div>)}</div>)}<small className="flight-provenance">Transcribed as displayed. Rounded taxi durations can differ from the minute-by-minute clock interval.</small></section>
 <section className="flight-info-card airline-info"><div className="airline-info-heading"><CarrierBadge carrier={f.carrier}/><div><h2>Cathay Pacific</h2><p>Oneworld</p></div></div><div className="airline-actions"><button onClick={()=>setSheet('more')}>PHONE</button><a href="https://www.cathaypacific.com/" target="_blank" rel="noreferrer">WEBSITE</a><button onClick={()=>setSheet('more')}>X / TWITTER</button><button onClick={()=>setSheet('more')}>FACEBOOK</button></div><div className="airline-codes"><div><small>ATC Callsign</small>CATHAY</div><div><small>ICAO</small>CPA</div><div><small>IATA</small>CX</div></div></section></>}
 <section className="flight-info-card route-history"><h2>My History on This Route</h2><p>{f.from} → {f.to}</p><div className="route-history-totals"><div><small>Flights</small><strong>{stats.count}</strong></div><div><small>Distance</small><strong>{stats.estimated?'≈ ':''}{stats.km.toLocaleString()} km</strong></div><div><small>Flight Time</small><strong>{duration(stats.minutes)}</strong></div></div><p>Most recent flights</p>{history.map(r=><button className="route-history-flight" key={r.id} onClick={()=>{if(r.id!==id)flow.push(screen('flight',r.id));}} aria-label={`${r.number}, ${date(r,true)}`}><CarrierBadge carrier={r.carrier}/><span><span><strong>{date(r,true)}</strong><strong>{r.number}</strong></span><span><small>{duration(r.minutes)}</small><small>{r.registration??'Unknown registration'} · {aircraftNames[flightMetadata(r).aircraft]??flightMetadata(r).aircraft}</small></span></span></button>)}{!history.length&&<p>No completed personal flights on this route.</p>}</section>
 {facts&&<section className="flight-info-card updates"><h2>Updates</h2><p>15 updates for this flight</p><div><span className="update-dot"/><strong>Departure from Terminal 1 · Gate 3</strong><small>Jan 2 at 5:04 PM</small></div><small className="flight-provenance">One update is visible in the reference. Its year and the remaining updates were not supplied.</small></section>}
 <button className="flight-info-card flight-note" onClick={()=>setSheet('edit')}><h2>Notes</h2><p>{app.state.flightNotes?.[id]||'Tap to Edit'}</p></button>
 <button className="report-flight" onClick={()=>setSheet('report')}><WarningCircle size={20}/>Report Data Issue</button>
 <p className="flight-provenance">{facts?'Flight details transcribed from your CX 882 screenshots.':f.source==='reference'?`Reference flight · ${f.distanceEstimated?'distance estimated; remaining details not supplied':'reported distance and recorded times'}.`:'Sample or manually entered flight details.'}</p>
 </div></div></PageBody></MapPanel>
 <div className="flight-detail-actions"><div><button aria-label="Edit flight details" onClick={()=>setSheet('edit')}><NotePencil size={27}/></button><button aria-label="More flight actions" onClick={()=>setSheet('more')}><DotsThree size={28}/></button></div><button className="flight-share" onClick={()=>setSheet('share')}><Export size={23}/>Share</button></div>
 <BottomSheet open={sheet!==null} onOpenChange={v=>!v&&closeSheet()} title={sheet==='edit'?'Edit flight details':sheet==='share'?'Share flight':sheet==='report'?'Report Data Issue':sheet==='connection'?'Connection at HKG':sheet==='aircraft'?'Flights on B-KPX':'Flight actions'} snap={sheet==='edit'?.8:.55}>
 {sheet==='edit'&&<><label className="field">Booking Code<KeyboardInput value={booking} onChange={e=>setBooking(e.target.value)} maxLength={20}/></label><label className="field">Seat<KeyboardInput value={seat} onChange={e=>setSeat(e.target.value)} maxLength={10}/></label><label className="field">Notes<KeyboardTextarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/></label><button className="primary" onClick={save}>Save details</button></>}
 {sheet==='share'&&<><p style={{whiteSpace:'pre-line'}}>{summary}</p><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(summary);app.toast('Flight summary copied');}catch{app.toast('Copy unavailable; use Download instead.');}}}><Copy/>Copy summary</button><button className="secondary" onClick={()=>download(summary,'flight-summary.txt')}>Download summary</button><p className="fineprint">Booking codes, seats and private notes are excluded.</p></>}
 {sheet==='connection'&&<p>The reference reports a 5h 15m connection, with 4h 25m above its suggested minimum. This is historical information, not current transfer guidance.</p>}
 {sheet==='aircraft'&&<><p>Counted from records with registration B-KPX. The supplied list contains two, although the detail screenshot says one.</p>{samePlane.map(r=><button className="menu-row" key={r.id} onClick={()=>{setSheet(null);if(r.id!==id)flow.push(screen('flight',r.id));}}>{r.number} · {date(r,true)}<CaretRight/></button>)}</>}
 {sheet==='more'&&<><p>Airline contact details are not connected in this local demo. The Website link opens Cathay Pacific’s official site.</p><button className="menu-row" onClick={()=>setSheet('edit')}><NotePencil/>Edit booking, seat and notes</button><button className="menu-row" onClick={()=>setSheet('report')}><Flag/>Prepare data issue report</button></>}
 {sheet==='report'&&<><p>Describe the issue and download a report. Nothing is sent to Flighty or the airline.</p><label className="field">Issue description<KeyboardTextarea value={report} onChange={e=>setReport(e.target.value)} maxLength={2000}/></label><button className="primary" disabled={!report.trim()} onClick={()=>{download(`${summary}\n\nIssue:\n${report}`,'flight-data-issue.txt');app.toast('Report downloaded');}}>Download report</button></>}
 <button className="text-button" onClick={closeSheet}>Done</button></BottomSheet></>;
}
function AirportTime({flight:f,departure=false,scheduled,delay,terminal}:{flight:Flight;departure?:boolean;scheduled?:string;delay?:number;terminal?:string}){const code=departure?f.from:f.to,Icon=departure?ArrowUpRight:ArrowDownRight;return <section className="flight-airport"><h2><Icon size={16}/>{code} · {airports[code].name}<CaretRight size={15}/></h2><div className="flight-airport-clock"><div><div><strong className={delay&&delay>0?'late':delay!==undefined?'early':''}>{f.dateOnly?'Time unavailable':localTime(departure?f.departure:f.arrival,code)}</strong>{scheduled&&<del>{localTime(scheduled,code)}</del>}</div>{delay!==undefined&&<p className={delay>0?'late':'early'}>{delay>0?`${delay}m Late`:delay<0?`${-delay}m Early`:'On Time'}</p>}</div><aside>{departure&&f.gate&&<strong><ArrowUpRight size={21}/>{f.gate}</strong>}{terminal&&<small>Terminal {terminal}</small>}</aside></div></section>;}
