import {airports,routeDistance,type Flight} from './domain.ts';
export const carriers=[{name:'United',code:'UA',icao:'UAL'},{name:'Southwest',code:'WN',icao:'SWA'},{name:'ANA',code:'NH',icao:'ANA'},{name:'Cathay Pacific',code:'CX',icao:'CPA'},{name:'Japan Airlines',code:'JL',icao:'JAL'},{name:'British Airways',code:'BA',icao:'BAW'},{name:'Delta',code:'DL',icao:'DAL'},{name:'Alaska Airlines',code:'AS',icao:'ASA'}];
export const demoDate='2026-09-15';
export function parseFlightNumber(value:string){const match=value.trim().toUpperCase().replace(/\s/g,'').match(/^([A-Z0-9]{2})(\d{1,4}[A-Z]?)$/);const carrier=carriers.find(c=>c.code===match?.[1]);return carrier&&match?{carrier,number:match[2]}:null;}
export function parseDepartureDate(value:string){const s=value.trim().toLowerCase();if(s==='today')return demoDate;if(s==='tomorrow')return '2026-09-16';if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s?s:null;}const md=s.match(/^(\d{1,2})\/(\d{1,2})$/);if(md)return parseDepartureDate(`2026-${md[1].padStart(2,'0')}-${md[2].padStart(2,'0')}`);const days=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];const day=days.indexOf(s);if(day>=0){const d=new Date(demoDate+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+(day-d.getUTCDay()+7)%7);return d.toISOString().slice(0,10);}return null;}
export const shortDate=(day:string)=>new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));
export const samples=[{code:'UA',number:'123',from:'LHR',to:'EWR',utc:'06:45',minutes:458},{code:'UA',number:'2148',from:'PIT',to:'ORD',utc:'13:00',minutes:100},{code:'WN',number:'2373',from:'SAN',to:'SFO',utc:'03:10',minutes:95},{code:'NH',number:'111',from:'ORD',to:'HND',utc:'16:50',minutes:800}];
export function sampleSearch(day:string,number='',from='',to=''){return samples.filter(s=>(!number||s.code+s.number===number.replace(/\s/g,'').toUpperCase())&&(!from||s.from===from)&&(!to||s.to===to)).map(s=>{const departure=new Date(`${day}T${s.utc}:00Z`);return {id:`sample-${s.code}${s.number}-${day}`,carrier:carriers.find(c=>c.code===s.code)!.name,number:`${s.code} ${s.number}`,from:s.from,to:s.to,departure:departure.toISOString(),arrival:new Date(+departure+s.minutes*60000).toISOString(),minutes:s.minutes,km:routeDistance(s.from,s.to),distanceEstimated:true,status:(day<demoDate?'flown':'planned') as Flight['status'],source:'sample' as const};});}
// This local sample itinerary is transcribed from the supplied Friends reference.
export const friendFlights:Flight[]=[
 {id:'bobo-1',from:'SAN',to:'SFO',carrier:'Southwest',number:'WN 2373',departure:'2026-09-25T20:10:00-07:00',arrival:'2026-09-25T21:45:00-07:00',minutes:95,km:0,status:'planned'},
 {id:'bobo-2',from:'SJC',to:'SAN',carrier:'Southwest',number:'WN 1794',departure:'2026-09-28T11:40:00-07:00',arrival:'2026-09-28T13:10:00-07:00',minutes:90,km:0,status:'planned'},
 {id:'bobo-3',from:'SAN',to:'OGG',carrier:'Alaska Airlines',number:'AS 249',departure:'2026-09-29T10:28:00-07:00',arrival:'2026-09-29T13:34:00-10:00',minutes:366,km:0,status:'planned'},
 {id:'bobo-4',from:'OGG',to:'LAS',carrier:'Alaska Airlines',number:'AS 932',departure:'2026-10-03T10:36:00-10:00',arrival:'2026-10-03T19:08:00-07:00',minutes:332,km:0,status:'planned'},
 {id:'bobo-5',from:'LAS',to:'SAN',carrier:'Alaska Airlines',number:'AS 2483',departure:'2026-10-03T20:23:00-07:00',arrival:'2026-10-03T21:50:00-07:00',minutes:87,km:0,status:'planned'},
].map(f=>({...f,status:'planned' as const,source:'sample',distanceEstimated:true,km:routeDistance(f.from,f.to)}));
export function connectionMinutes(a:Flight,b:Flight){return a.to===b.from?Math.round((Date.parse(b.departure)-Date.parse(a.arrival))/60000):null;}
export function localTime(iso:string,code:string){return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:airports[code].zone}).format(new Date(iso));}
