import {useEffect,useState} from 'react';
import {AirplaneTilt,ArrowRight,CaretRight,Copy,Plus,UserCircle,Users,X} from '@phosphor-icons/react';
import {BottomSheet,Carousel,useFlow} from './mobile';
import {CarrierBadge,PageBody,screen,useApp} from './Prototype';
import {airports,duration,type Flight} from './domain';
import {connectionMinutes,demoDate,friendFlights,localTime} from './flightCatalog';
import RouteMap from './RouteMap';

export default function FriendsView({detail=false}:{detail?:boolean}){
 const app=useApp(),flow=useFlow();const [filter,setFilter]=useState('Everyone'),[intro,setIntro]=useState(false),[share,setShare]=useState(false),[connection,setConnection]=useState<number|null>(null);
 useEffect(()=>{if(!detail&&!app.state.friends?.includes('bobo')&&new URLSearchParams(location.search).get('preview-friend')==='bobo')setIntro(true);},[]);
 const added=app.state.friends?.includes('bobo')??false,shown=added?friendFlights.filter(f=>filter!=='Today'||new Intl.DateTimeFormat('en-CA',{timeZone:airports[f.from].zone}).format(new Date(f.departure))===demoDate):[];
 const addSample=()=>{if(app.save({...app.state,friends:[...new Set([...(app.state.friends??[]),'bobo'])]},'Bobo added as a sample friend')){setShare(false);setIntro(false);setFilter('Everyone');}};
 const days=(f:Flight)=>Math.round((Date.parse(f.departure.slice(0,10)+'T12:00:00Z')-Date.parse(demoDate+'T12:00:00Z'))/86400000);
 return <><PageBody>{detail&&<RouteMap flights={friendFlights} compact/>}<div className="friends-content">{detail?<div className="friend-profile"><UserCircle size={60}/><h1>Bobo</h1><p>Sample friend · {friendFlights.length} upcoming flights</p><button className="text-button" onClick={()=>{app.save({...app.state,friends:(app.state.friends??[]).filter(id=>id!=='bobo')},'Sample friend removed');flow.replace(screen('friends'));}}>Remove friend</button></div>:<Carousel className="friends-filter-rail" ariaLabel="Friends filters"><div className="friends-filters"><button aria-pressed={filter==='Everyone'} onClick={()=>setFilter('Everyone')}>Everyone</button><button aria-pressed={filter==='Today'} onClick={()=>setFilter('Today')}>Today</button>{added&&<button aria-label="Bobo’s profile" onClick={()=>flow.push(screen('friend','bobo'))}><UserCircle size={22}/>Bobo</button>}<button onClick={()=>setIntro(true)}><Plus size={21}/>Add Friend</button></div></Carousel>}

 {shown.map((f,i)=>{const gap=i>0?connectionMinutes(shown[i-1],f):null;return <div key={f.id}>{gap!==null&&gap>0&&gap<48*60&&<button className="friend-connection" onClick={()=>setConnection(gap)}><span>{duration(gap)} at {f.from}</span><span>{gap>6*60?'Long Connection':'Normal'}<CaretRight size={16}/></span></button>}<button className="friend-flight" onClick={()=>flow.push(screen('flight',f.id))}><span className="friend-flight-avatar"><UserCircle size={43} weight="duotone"/><small>{days(f)} DAYS</small></span><span className="friend-flight-copy"><span className="section-heading"><span className="friend-number"><CarrierBadge carrier={f.carrier}/>{f.number}</span><time>{new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:airports[f.from].zone}).format(new Date(f.departure))}</time></span><strong>{airports[f.from].city} to {airports[f.to].city}</strong><span className="friend-times">↗ {f.from} <b>{localTime(f.departure,f.from)}</b><span>↘ {f.to} <b>{localTime(f.arrival,f.to)}</b></span></span></span></button></div>;})}
 {!shown.length&&<section className="friends-empty"><Users size={38}/><h2>{added?'No flights today':'Add Friends’ Flights'}</h2><p>{added?'Bobo’s next flight is September 25.':'Add a Flighty friend to see their flights automatically, or tap Search to add a flight.'}</p>{added&&<button className="text-button" onClick={()=>setFilter('Everyone')}>Show upcoming flights</button>}</section>}
 <p className="fineprint">{added?'Sample itinerary from your reference · not live tracking':'Friends preview · no accounts connected'}</p></div></PageBody>
 <BottomSheet open={intro} onOpenChange={setIntro} title="" snap={.94}><div className="friends-intro"><button className="header-circle intro-close" aria-label="Close Friends introduction" onClick={()=>setIntro(false)}><X size={28}/></button><img src="/assets/friends/onboarding.png" alt="Friends’ flight updates around the globe"/><h1>Flighty Friends</h1><p>Add friends and family to automatically share upcoming flights, see each other fly on the map, and get live updates when flights take off, land, or change.</p><p>It’s free, and saves you from ever hearing “Send me your flight info!” again.</p><small>Try the flow with a sample friend. This local demo does not send invitations or live updates.</small><button className="primary" onClick={()=>setShare(true)}>Continue</button></div></BottomSheet>
 <BottomSheet open={share} onOpenChange={setShare} title="Share Flights" description="Preview invitation · no message is sent" snap={.56}><div className="friend-share"><div className="share-app"><AirplaneTilt size={40} weight="fill"/><strong>Flighty Friends</strong></div><p>Invite friends to share their upcoming flights.</p><div className="share-preview"><UserCircle size={38}/><span>Bobo<small>Sample friend</small></span></div><button className="menu-row" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?preview-friend=bobo`);app.toast('Demo preview link copied');}catch{app.toast('Copy unavailable in this browser.');}}}><Copy/>Copy demo preview link</button><button className="primary" onClick={addSample}>Add sample friend Bobo<ArrowRight/></button><button className="text-button" onClick={()=>setShare(false)}>Cancel</button></div></BottomSheet>
 <BottomSheet open={connection!==null} onOpenChange={v=>!v&&setConnection(null)} title="Connection" snap={.4}><p>{duration(connection)} between the arrival of one flight and departure of the next, calculated in UTC.</p><p>Sample connection guidance. Check the airline’s current airport and transfer information.</p><button className="secondary" onClick={()=>setConnection(null)}>Done</button></BottomSheet></>;
}
