import {useState} from 'react';
import {CaretRight,Plus,PushPin,AirplaneTilt,CheckCircle} from '@phosphor-icons/react';
import {BottomSheet,KeyboardInput,KeyboardTextarea,useKeyboard} from './mobile';
import {useApp,CarrierBadge} from './Prototype';
import {programs,accountsFor,creditsFor,progressFor,validAccount,type LoyaltyAccount,type FlightCredit} from './loyalty';
import {date,type Flight} from './domain';
const n=(v:number)=>v.toLocaleString();
export default function LoyaltyHub(){
 const app=useApp(),[open,setOpen]=useState(false),[edit,setEdit]=useState<LoyaltyAccount|null>(null),[adding,setAdding]=useState(false),[flight,setFlight]=useState<Flight|null>(null);
 const accounts=app.state.empty?[]:accountsFor(app.state),credits=creditsFor(app.state),selected=accounts.find(a=>a.id===app.state.pinnedProgram)??accounts[0];
 return <section className="loyalty-hub"><div className="section-heading"><h2>Mileage & status</h2><button className="text-button" onClick={()=>setOpen(true)}>View all<CaretRight size={14}/></button></div>{selected?<AccountCard account={selected} compact onClick={()=>setOpen(true)}/>:<button className="loyalty-empty" onClick={()=>setOpen(true)}><Plus/><span>Add a loyalty account<small>Track your balance and next goal</small></span><CaretRight/></button>}
 <BottomSheet open={open} onOpenChange={setOpen} title="Your loyalty programs" description="Balances and status goals, separate from distance flown." snap={.9}>
 {accounts.map(a=><div key={a.id}><AccountCard account={a} onClick={()=>{setOpen(false);setEdit(a);}}/><div className="loyalty-card-actions"><button onClick={()=>{setOpen(false);setEdit(a);}}>Edit account & goal</button><button aria-label={`Pin ${programs.find(p=>p.id===a.program)?.name}`} onClick={()=>app.save({...app.state,pinnedProgram:a.id},'Program pinned to My Flights')}><PushPin weight={selected?.id===a.id?'fill':'regular'}/>Pin</button></div></div>)}
 <button className="secondary" onClick={()=>{setOpen(false);setAdding(true);}}><Plus/>Add account manually</button><h3>Flight credit</h3><p className="muted">Choose the program receiving credit, even when you fly another airline.</p>{(app.state.empty?[]:app.records).filter(f=>f.status!=='canceled').sort((a,b)=>b.departure.localeCompare(a.departure)).map(f=><button key={f.id} className="menu-row credit-flight" onClick={()=>{setOpen(false);setFlight(f);}}><CarrierBadge carrier={f.carrier}/><span>{f.number} · {f.from} → {f.to}<small>{date(f,true)} · {credits[f.id]?.stage??'Not assigned'}</small></span><CaretRight/></button>)}<p className="fineprint">Stored on this device. No live account connection. Back up your data from Demo controls.</p><button className="secondary" onClick={()=>setOpen(false)}>Done</button></BottomSheet>
 {(adding||edit)&&<AccountEditor account={edit} onClose={()=>{setAdding(false);setEdit(null);setOpen(true);}}/>}{flight&&<CreditEditor flight={flight} onClose={()=>{setFlight(null);setOpen(true);}}/>}
 </section>;
}
function AccountCard({account:a,compact=false,onClick}:{account:LoyaltyAccount;compact?:boolean;onClick:()=>void}){
 const app=useApp(),p=programs.find(p=>p.id===a.program)!,v=progressFor(a,creditsFor(app.state),app.state.empty?[]:app.records),unit=a.goal==='redeem'?(p.currency??'miles'):p.unit;
 return <button className={`loyalty-card ${compact?'compact':''}`} onClick={onClick}><div className="section-heading"><span className="benefit-carrier"><CarrierBadge carrier={p.carrier}/><strong>{p.name}</strong></span><CaretRight size={18}/></div><div className="loyalty-meta">{a.source==='sample'?'Sample account':'Entered manually'} · Updated {a.updated}</div><div className="loyalty-goal">{a.goal==='retain'?'Retain':a.goal==='redeem'?'Save for':'Reach'} {a.goalName}<span>{a.end}</span></div><div className="loyalty-number"><strong>{n(v.current)}</strong><span> / {n(a.target)} {unit}</span></div><progress value={v.current} max={a.target} aria-label={`${p.name} ${unit} goal`}/><p className="loyalty-remaining">{v.expired?'Goal period ended':`${n(v.remaining)} ${unit} to your goal`}</p>{a.goal!=='redeem'&&a.secondTarget>0&&<div className="secondary-counter"><span>{p.second}</span><strong>{n(a.second)} / {n(a.secondTarget)}</strong></div>}<div className="credit-projection"><span>Pending <b>+{n(v.waiting)}</b></span><span>Booked estimate <b>+{n(v.expected)}</b></span></div>{(v.expected>0||v.waiting>0)&&<p className="projection-copy">After these credits: {n(v.projectedRemaining)} {unit} remaining{a.secondTarget>0?`; ${n(Math.max(0,a.secondTarget-v.secondProjected))} ${p.second} remaining`:''}.</p>}{v.unknown&&<p className="projection-copy">Some credit amounts are unknown. The projection is incomplete.</p>}{v.rows.some(r=>r.credit.stage==='missing')&&<p className="projection-copy">Missing flight credit needs review.</p>}{!compact&&<><div className="redeemable-balance"><span>Redeemable balance</span><strong>{n(a.balance)} {p.currency??'miles'}</strong></div><p className="fineprint">{a.rule==='ana-platinum'?'ANA flying-only Platinum requirements: both counters must be met.':a.source==='sample'?'Illustrative personal target; not an airline qualification or award price.':'Personal goal entered by you; check all airline qualification conditions.'} {a.goal==='redeem'?'Reward availability and pricing must be checked with the airline.':''} Posted flight credits are already included in your entered balance.</p></>}</button>;
}
function AccountEditor({account,onClose}:{account:LoyaltyAccount|null;onClose:()=>void}){
 const app=useApp(),keyboard=useKeyboard();const [a,setA]=useState<LoyaltyAccount>(account??{id:'account-'+Date.now(),program:'ana',balance:0,status:0,second:0,goal:'reach',goalName:'Platinum',target:50000,secondTarget:25000,start:'2026-01-01',end:'2026-12-31',updated:new Date().toISOString().slice(0,10),source:'manual',rule:'ana-platinum'}),[error,setError]=useState('');const p=programs.find(p=>p.id===a.program)!;const update=(v:Partial<LoyaltyAccount>)=>setA({...a,...v});const close=()=>{keyboard.hide();onClose();};
 const num=(key:'balance'|'status'|'second'|'target'|'secondTarget',label:string)=><label className="field">{label}<KeyboardInput inputMode="numeric" value={String(a[key])} onChange={e=>update({[key]:Number(e.target.value),...(['target','secondTarget'].includes(key)?{rule:'personal' as const}:{})})}/></label>;
 return <BottomSheet open onOpenChange={v=>!v&&close()} title={account?'Edit account & goal':'Add loyalty account'} snap={.94}><div className="loyalty-form"><label className="field">Program<select aria-label="Program" value={a.program} onChange={e=>update({program:e.target.value,balance:0,status:0,second:0,rule:'personal',goalName:'My status goal',target:0,secondTarget:0})}>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="choice-segments" aria-label="Goal type">{(['reach','retain','redeem'] as const).map(g=><button key={g} aria-pressed={a.goal===g} onClick={()=>update({goal:g,rule:'personal',goalName:g==='redeem'?'Reward flight':a.goalName,secondTarget:g==='redeem'?0:a.secondTarget})}>{g==='reach'?'Reach status':g==='retain'?'Retain status':'Save miles'}</button>)}</div>{a.program==='ana'&&a.goal!=='redeem'&&<button className="text-button" onClick={()=>update({rule:'ana-platinum',goalName:'Platinum',target:50000,secondTarget:25000})}>Use ANA Platinum requirements</button>}<label className="field">Goal name<KeyboardInput value={a.goalName} maxLength={60} onChange={e=>update({goalName:e.target.value})}/></label>{num('balance',`Redeemable ${p.currency??'miles'} balance`)}{a.goal!=='redeem'&&num('status',`${p.unit} already credited`)}{num('target',a.goal==='redeem'?`${p.currency??'Miles'} savings target`:`${p.unit} target`)}{a.goal!=='redeem'&&<>{num('second',`${p.second} already credited`)}{num('secondTarget',`${p.second} target (0 if not required)`)}</>}<div className="date-pair"><label className="field">Period starts<KeyboardInput type="date" value={a.start} onChange={e=>update({start:e.target.value,rule:'personal'})}/></label><label className="field">Goal deadline<KeyboardInput type="date" value={a.end} onChange={e=>update({end:e.target.value,rule:'personal'})}/></label></div><p className="fineprint">Enter totals from your airline account. These totals already include posted flight credits. Estimated and pending amounts are displayed separately.</p>{a.rule==='ana-platinum'&&<a className="text-button" target="_blank" rel="noreferrer" href="https://www.ana.co.jp/en/jp/amc/premium/overview/premium-point/">ANA qualification rules · checked Sep 15, 2026</a>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" onClick={()=>{try{validAccount(a);const next={...a,source:'manual' as const,updated:new Date().toISOString().slice(0,10)};if(app.save({...app.state,loyaltyAccounts:[...accountsFor(app.state).filter(x=>x.id!==a.id),next]},'Account and goal saved'))close();}catch(e){setError((e as Error).message);}}}>Save account</button><button className="text-button" onClick={close}>Cancel</button></div></BottomSheet>;
}
export function CreditEditor({flight:f,onClose}:{flight:Flight;onClose:()=>void}){
 const app=useApp(),keyboard=useKeyboard(),accounts=accountsFor(app.state),[credit,setCredit]=useState<FlightCredit>(creditsFor(app.state)[f.id]??{accountId:accounts[0]?.id??'',stage:f.status==='planned'?'estimated':'missing',miles:null,points:null,second:null,note:'',updated:''}),[error,setError]=useState('');const a=accounts.find(a=>a.id===credit.accountId),p=programs.find(p=>p.id===a?.program);const close=()=>{keyboard.hide();onClose();};
 return <BottomSheet open onOpenChange={v=>!v&&close()} title={`${f.number} · Flight credit`} snap={.9}><p>{f.from} → {f.to} · {date(f,true)}</p><label className="field">Credit to<select aria-label="Credit to" value={credit.accountId} onChange={e=>setCredit({...credit,accountId:e.target.value,miles:null,points:null,second:null})}>{accounts.map(a=><option key={a.id} value={a.id}>{programs.find(p=>p.id===a.program)?.name}{a.source==='sample'?' (sample)':''}</option>)}</select></label>{!accounts.length&&<p>Add a loyalty account from My Flights first.</p>}<label className="field">Credit state<select aria-label="Credit state" value={credit.stage} onChange={e=>setCredit({...credit,stage:e.target.value as FlightCredit['stage']})}>{(f.status==='planned'?['estimated']:['missing','pending','posted']).map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></label>{(['miles','points','second'] as const).map((key,i)=><label className="field" key={key}>{i===0?`Redeemable ${p?.currency??'miles'}`:i===1?p?.unit??'Status points':p?.second??'Additional credit'}<KeyboardInput inputMode="numeric" placeholder="Unknown" value={credit[key]??''} onChange={e=>setCredit({...credit,[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}<label className="field">Estimate source / note<KeyboardTextarea aria-label="Estimate source / note" placeholder="e.g. airline calculator, fare class, statement" value={credit.note} maxLength={500} onChange={e=>setCredit({...credit,note:e.target.value})}/></label><p className="fineprint">Use your airline’s calculator or statement. Distance alone cannot predict earnings. Posted credits do not add to your balance again; update the account total separately.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!accounts.length} onClick={()=>{if(![credit.miles,credit.points,credit.second].every(v=>v===null||(Number.isFinite(v)&&v>=0))){setError('Enter non-negative amounts, or leave unknown amounts blank.');return;}if(app.save({...app.state,flightCredits:{...creditsFor(app.state),[f.id]:{...credit,updated:new Date().toISOString().slice(0,10)}}},'Flight credit saved'))close();}}>Save flight credit</button><button className="text-button" onClick={close}>Cancel</button></BottomSheet>;
}
export function TripCredits({flights}:{flights:Flight[]}){
 const app=useApp(),[edit,setEdit]=useState<Flight|null>(null),credits=creditsFor(app.state),accounts=accountsFor(app.state),rows=flights.filter(f=>f.status!=='canceled');
 return <section className="trip-credit-section"><h2>Mileage for this trip</h2><p className="muted">Credit by program · separate from flown distance</p>{accounts.map(a=>{const entries=rows.filter(f=>credits[f.id]?.accountId===a.id);if(!entries.length)return null;const p=programs.find(p=>p.id===a.program)!;return <div className="trip-program" key={a.id}><strong>{p.name}</strong>{(['posted','pending','estimated','missing'] as const).map(stage=>{const cs=entries.map(f=>credits[f.id]).filter(c=>c.stage===stage);return cs.length?<p key={stage}>{stage} · {cs.length} flights · {cs.some(c=>c.miles===null)?'Incomplete miles':n(cs.reduce((n,c)=>n+(c.miles??0),0))+' '+(p.currency??'miles')}</p>:null;})}</div>;})}{rows.map(f=><button className="menu-row" key={f.id} onClick={()=>setEdit(f)}><AirplaneTilt/><span>{f.number}<small>{credits[f.id]?.stage??'Choose credited program'}</small></span><CaretRight/></button>)}{edit&&<CreditEditor flight={edit} onClose={()=>setEdit(null)}/>}</section>;
}
