import {SealCheck,LockSimple,CheckCircle,Clock,ArrowUpRight,Medal} from '@phosphor-icons/react';
import type {LoyaltyAccount} from './loyalty';
import {membershipState,membershipValid,policyFor,policyChecked,type Perk} from './benefitPolicy';
import './membership.css';
export function TierBadge({account,day,compact=false}:{account:LoyaltyAccount;day:string;compact?:boolean}){
 const policy=policyFor(account),active=membershipValid(account,day),state=membershipState(account,day);
 return <span className={`tier-badge ${active?policy?.tone??'neutral':'neutral'} ${compact?'small':''}`} aria-label={`${account.currentTier??'Membership'} · ${state}`}><span className="tier-emblem">{active?<SealCheck size={compact?20:30} weight="duotone"/>:<Medal size={compact?20:30}/>}</span><span><strong>{policy?.tier??account.currentTier??'Add your tier'}</strong>{!compact&&<small>{state}</small>}</span></span>;
}
export function PolicyPerks({perks}:{perks:Perk[]}){return <ul className="policy-perks">{perks.map(p=><li key={p.id}><span className={`policy-perk-icon ${p.kind}`}>{p.kind==='included'?<CheckCircle size={19}/>:<Clock size={19}/>}</span><div><strong>{p.label}</strong><span>{p.reason}</span><small>{p.scope}{p.kind==='paid'?' · Miles / points required':''}</small></div></li>)}</ul>;}
export function PolicyLinks({perks}:{perks:Perk[]}){const links=[...new Set(perks.map(p=>p.source))];return <details className="policy-sources"><summary>Policy details & sources</summary><p>Selected benefits · checked {policyChecked}. Attach your membership to the booking and confirm eligibility for each flight.</p>{links.map((url,i)=><a key={url} href={url} target="_blank" rel="noopener noreferrer">{links.length===1?'Official benefit policy':`Official policy ${i+1}`}<ArrowUpRight size={15}/></a>)}</details>;}
export function AccountBenefits({account:a,day}:{account:LoyaltyAccount;day:string}){const p=policyFor(a),active=membershipValid(a,day);return <div className="account-benefits"><h3>{active?'Your membership benefits':'Membership details'}</h3>{p&&active?<><PolicyPerks perks={p.perks.filter(x=>x.kind!=='paid')}/>{p.perks.some(x=>x.kind==='paid')&&<details className="benefit-extra"><summary>With miles or Upgrade Points</summary><PolicyPerks perks={p.perks.filter(x=>x.kind==='paid')}/></details>}<PolicyLinks perks={p.perks}/></>:<p className="benefit-explanation">{!active?'Enter the tier and validity dates shown in your airline account to see current benefits.':'This tier is saved. Its benefit policy is not yet in this demo’s catalog.'}</p>}{p?.next&&<details className="next-tier-preview"><summary><LockSimple size={19}/><span>Next tier · <strong>{p.next.tier}</strong></span></summary><PolicyPerks perks={p.next.perks}/><p className="benefit-explanation">{a.rule==='ana-platinum'?'Both ANA qualification counters must be met.':a.goal==='redeem'?'Your miles savings goal is separate from status qualification.':'Your personal flying target does not confirm qualification for this tier.'} New benefits start after the airline confirms and activates your status.</p><PolicyLinks perks={p.next.perks}/></details>}</div>;}
