import {useState} from 'react';
import {ArrowRight,ArrowsLeftRight,CheckCircle,CaretRight,SlidersHorizontal,AirplaneTilt,Info,Sparkle} from '@phosphor-icons/react';
import {BottomSheet,KeyboardInput,MobileScroll,useKeyboard} from './mobile';
import {useApp,CarrierBadge} from './Prototype';
import {airports,duration} from './domain';
import {accountsFor,programs,type LoyaltyAccount} from './loyalty';
import {airportInput,benefitsFor,displayAccount,progressSegments,bookingSites,earningSources,cabins,money,offersFor,projectionFor,rankOffers,validateQuery,type PlannerQuery,type Priority,type Offer} from './planner';
import './planner.css';
import {TierBadge,PolicyPerks,PolicyLinks} from './MembershipBenefits';
import {saveLastSearch} from './plannerHistory';
import {offerOperators} from './benefitPolicy';
const n=(v:number)=>v.toLocaleString('en-US');
function GrowthBar({current,earned,target,unit}:{current:number;earned:number;target:number;unit:string}){const widths=progressSegments(current,earned,target);return <div className="growth-chart"><div className="growth-track" role="img" aria-label={`${n(current)} current + ${n(earned)} projected ${unit}; target ${n(target)}`}><span className="growth-current" style={{width:`${widths.current}%`}}/><span className="growth-earned" style={{width:`${widths.earned}%`}}/></div><div className="growth-legend"><span><i/>Current {n(current)}</span><span><i/>This trip +{n(earned)}</span></div></div>;}
const shortDate=(day:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(day));
const unitFor=(a:LoyaltyAccount)=>{const p=programs.find(p=>p.id===a.program)!;return a.goal==='redeem'?(p.currency??'miles'):p.unit;};

export default function MileagePlanner({initialDestination=''}:{initialDestination?:string}){
 const app=useApp(),keyboard=useKeyboard(),accounts=app.state.empty?[]:accountsFor(app.state);
 const [from,setFrom]=useState(app.state.homeBases?.[0]??'PIT'),[to,setTo]=useState(initialDestination),[depart,setDepart]=useState('2026-10-07'),[returnDate,setReturnDate]=useState('2026-10-17'),[roundTrip,setRoundTrip]=useState(true);
 const [query,setQuery]=useState<PlannerQuery|null>(null),[editing,setEditing]=useState(false),[cabin,setCabin]=useState<PlannerQuery['cabin']>('Economy'),[searchCabin,setSearchCabin]=useState<PlannerQuery['cabin']>('Economy'),[priority,setPriority]=useState<Priority>('price'),[nonstop,setNonstop]=useState(false),[goalId,setGoalId]=useState(app.state.pinnedProgram??accounts[0]?.id??''),[error,setError]=useState(''),[selected,setSelected]=useState<Offer|null>(null);
 const goal=accounts.find(a=>a.id===goalId),q=query?{...query,cabin,nonstop}:null,offers=q?offersFor(q):[],ranked=q?rankOffers(offers,q,priority,goal,accounts):[],cheapest=offers.length?Math.min(...offers.map(o=>o.price)):0;
 const search=()=>{keyboard.hide();const candidate={from:airportInput(from),to:airportInput(to),depart,returnDate,roundTrip,cabin:searchCabin,nonstop};const issue=validateQuery(candidate);if(issue){setError(issue);return;}saveLastSearch(airports[candidate.to].city);setError('');setQuery(candidate);setCabin(searchCabin);setEditing(false);};
 const editSearch=()=>{if(q){setFrom(q.from);setTo(q.to);setDepart(q.depart);setReturnDate(q.returnDate);setRoundTrip(q.roundTrip);setSearchCabin(q.cabin);}setError('');setEditing(true);};
 const form=<div className="planner-form"><div className="choice-segments" aria-label="Journey type">{[true,false].map(v=><button key={String(v)} type="button" aria-pressed={roundTrip===v} onClick={()=>{keyboard.hide();setRoundTrip(v);}}>{v?'Round trip':'One way'}</button>)}</div><div className="planner-route-fields"><label className="field">From<KeyboardInput aria-label="Departure city or airport" value={from} onChange={e=>setFrom(e.target.value)} placeholder="Pittsburgh or PIT"/></label><ArrowsLeftRight size={20}/><label className="field">To<KeyboardInput aria-label="Destination city or airport" value={to} onChange={e=>setTo(e.target.value)} placeholder="Tokyo or HND"/></label></div><div className="planner-quick" aria-label="Frequent routes">{['Tokyo','London','Chicago'].map(city=><button onClick={()=>{keyboard.hide();setTo(city);}} key={city}>{city}</button>)}</div><div className="date-pair"><label className="field">Departure date<KeyboardInput type="date" aria-label="Departure date" value={depart} onChange={e=>setDepart(e.target.value)}/></label>{roundTrip&&<label className="field">Return date<KeyboardInput type="date" aria-label="Return date" value={returnDate} onChange={e=>setReturnDate(e.target.value)}/></label>}</div><label className="field">Cabin<select aria-label="Search cabin" value={searchCabin} onChange={e=>setSearchCabin(e.target.value as typeof cabin)}>{cabins.map(c=><option key={c}>{c}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" onClick={search}>Compare flights<ArrowRight size={19}/></button><p className="planner-caption">Sample routes from Pittsburgh or San Francisco to Tokyo, London and Chicago. One adult · cash fares in USD.</p>{editing&&<button className="text-button" onClick={()=>{keyboard.hide();setEditing(false);setError('');}}>Cancel changes</button>}</div>;
 return <><MobileScroll className="planner-scroll"><main className="planner-page">
 {!q?<><span className="planner-eyebrow"><Sparkle size={15}/> A LITTLE MORE FROM EVERY FLIGHT</span><h1>Make your next<br/>flight count.</h1><p className="planner-intro">Compare the cost, the perks, and the progress toward your next goal.</p><div className="planner-notice"><Info size={18}/><span>Plan your next flight<small>Sample fares, calculated base earnings. Compare without changing your balance.</small></span></div>{form}</>:<>
 <button className="planner-search-summary" onClick={editSearch} aria-label="Edit trip search"><span><small>{q.roundTrip?'ROUND TRIP':'ONE WAY'} · 1 ADULT</small><strong>{q.from}<ArrowRight size={20}/>{airports[q.to].city}</strong><small>{shortDate(q.depart)}{q.roundTrip?` – ${shortDate(q.returnDate)}`:''} · {q.depart.slice(0,4)}{q.roundTrip&&q.depart.slice(0,4)!==q.returnDate.slice(0,4)?` / ${q.returnDate.slice(0,4)}`:''}</small></span><SlidersHorizontal size={23}/></button>
 <div className="planner-cabins" role="group" aria-label="Cabin">{cabins.map(c=><button aria-pressed={cabin===c} key={c} onClick={()=>setCabin(c)}>{c==='Premium economy'?'Premium':c}</button>)}</div>
 <div className="planner-filters"><label>Prioritize<select aria-label="Prioritize" value={priority} onChange={e=>setPriority(e.target.value as Priority)}><option value="price">Lowest cost</option><option value="goal" disabled={!accounts.length}>My goal</option><option value="benefits">My status benefits</option></select></label><button role="switch" aria-checked={nonstop} className={nonstop?'nonstop active':'nonstop'} onClick={()=>setNonstop(!nonstop)}>Nonstop{nonstop&&<CheckCircle size={15}/>}</button></div>
 {accounts.length>0&&<label className="planner-goal-select">Your goal<select aria-label="Comparison goal" value={goalId} onChange={e=>setGoalId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{programs.find(p=>p.id===a.program)?.carrier} · {a.goalName}</option>)}</select></label>}
 {priority==='benefits'&&<p className="planner-caption">More of your route covered by current tier benefits first; ties use the lowest fare. Availability and policy conditions still apply.</p>}<div className="planner-results-heading"><h2>{ranked.length?`${ranked.length} options to explore`:'No sample options'}</h2><span>Sample fares</span></div><p className="planner-caption">{q.roundTrip?'Return':'One-way'} total · USD / adult · taxes & listed bags included. Base earnings calculated for the assumed fare classes.</p>
 {!ranked.length?<div className="planner-empty"><AirplaneTilt size={36}/><h3>Let’s try another scenario.</h3><p>{nonstop?'No nonstop sample matches these choices.':cabin!=='Economy'&&q.to==='ORD'?'Chicago currently has Economy samples only.':'This route is not in our sample library yet.'}</p>{nonstop&&<button className="secondary" onClick={()=>setNonstop(false)}>Include connections</button>}<button className="secondary" onClick={()=>{setFrom('PIT');setTo('Tokyo');setCabin('Economy');setNonstop(false);setQuery({...q,from:'PIT',to:'HND',cabin:'Economy',nonstop:false});}}>Try Pittsburgh to Tokyo</button><button className="text-button" onClick={editSearch}>Change search</button></div>:ranked.map((o,i)=>{
 const v=projectionFor(goal,o,q),shownAccount=displayAccount(accounts,o,goal),shown=projectionFor(shownAccount,o,q),credit=o.credits.find(c=>c.program===shownAccount?.program)??o.credits[0],program=programs.find(p=>p.id===credit.program),benefits=benefitsFor(o,q,accounts);
 const reason=priority==='goal'?(v?.improvement?`${n(v.earned)} ${goal?unitFor(goal):''} toward your goal${v.met?' · target reached in this scenario':''}`:v?'No additional progress in this goal period':'Does not advance your selected goal'):priority==='benefits'?benefits.tierModeled?`${benefits.tier} benefits on ${benefits.scope} · ${o.price===cheapest?'lowest fare':money(o.price-cheapest)+' more than the lowest fare'}`:'No matching tier policy for this itinerary':`${o.price===cheapest?'Lowest sample price':`${money(o.price-cheapest)} more than the lowest price`}`;
 return <button className={`planner-offer ${i===0?'recommended':''}`} key={o.id} onClick={()=>setSelected(o)} aria-label={`Explore ${o.carrier} option`}>
 {i===0&&<span className="offer-recommendation"><Sparkle size={14}/>{priority==='goal'&&v?.improvement?'Strongest goal progress':priority==='benefits'?(benefits.tierModeled?'Your tier applies':'Lowest fare · no tier match'):'Lowest sample price'}</span>}
 <div className="offer-title"><CarrierBadge carrier={o.carrier}/><span><strong>{o.carrier}</strong><small>{o.route.length===2?'Nonstop':`1 stop · ${o.route[1]}`} · {duration(o.minutes)}</small></span><b>{money(o.price)}<small>{q.roundTrip?'round trip':'one way'}</small></b></div>{!(priority==='price'&&i===0)&&<p className="offer-reason">{reason}</p>}
 <div className="offer-credit"><span>Earn in {program?.name}<strong>+{n(credit.miles*(q.roundTrip?2:1))} {program?.currency??'miles'}</strong></span><CaretRight size={19}/></div><small className="offer-calculation-label">Calculated base earnings · bonuses excluded</small>{shownAccount&&shown&&<><GrowthBar current={shown.current} earned={shown.earned} target={shownAccount.target} unit={unitFor(shownAccount)}/><small className="offer-goal-label">{shownAccount.goalName} · {n(shownAccount.target)} {unitFor(shownAccount)}{!v&&goal?` · No ${programs.find(p=>p.id===goal.program)?.carrier} goal credit`:''}</small>{shownAccount.goal!=='redeem'&&shownAccount.secondTarget>0&&<small className="offer-goal-label">{n(shown.secondRemaining)} {programs.find(p=>p.id===shownAccount.program)?.second} still needed</small>}</>}{benefits.account&&<div className="offer-membership"><TierBadge account={benefits.account} day={q.depart} compact/><span>On {benefits.scope}</span></div>}<div className="offer-perks policy-preview">{benefits.perks.find(p=>p.kind!=='paid')?.label??'Compare fare details'}{benefits.perks.find(p=>p.kind!=='paid')?.kind==='conditional'?' · conditions apply':''}</div><p className="offer-policy-note">{o.bags} checked {o.bags===1?'bag':'bags'} in this fare scenario</p></button>;
 })}
 <p className="planner-caption planner-bottom-note">Outbound journey times shown. Your accounts stay unchanged while you compare. Confirm actual earnings and benefits with the airline.</p></>}
 </main></MobileScroll>
 <BottomSheet open={editing} onOpenChange={v=>{if(!v)keyboard.hide();setEditing(v);}} title="Edit your trip" snap={.94}>{form}</BottomSheet>
 {selected&&q&&<OfferDetails key={selected.id} offer={selected} query={q} accounts={accounts} preferred={goalId} cheapest={cheapest} onClose={()=>setSelected(null)}/>}
 </>;
}
function OfferDetails({offer:o,query:q,accounts,preferred,cheapest,onClose}:{offer:Offer;query:PlannerQuery;accounts:LoyaltyAccount[];preferred:string;cheapest:number;onClose:()=>void}){
 const eligibleAccounts=accounts.filter(a=>o.credits.some(c=>c.program===a.program));
 const [accountId,setAccountId]=useState(eligibleAccounts.find(a=>a.id===preferred)?.id??eligibleAccounts[0]?.id??'');
 const a=eligibleAccounts.find(a=>a.id===accountId),credit=o.credits.find(c=>c.program===a?.program)??o.credits[0],p=programs.find(p=>p.id===credit.program),v=projectionFor(a,o,q),benefits=benefitsFor(o,q,accounts),nights=Math.round((Date.parse(q.returnDate)-Date.parse(q.depart))/86400000);
 return <BottomSheet open onOpenChange={v=>!v&&onClose()} title="Your flight, your benefits" description="Sample fare · calculated base earnings" snap={.94}><div className="planner-detail"><div className="offer-title"><CarrierBadge carrier={o.carrier}/><span><strong>{o.carrier}</strong><small>{o.cabin} · {q.roundTrip?'Round trip':'One way'}</small></span><b>{money(o.price)}<small>USD total</small></b></div><p className="detail-route">{o.route.join(' → ')}{q.roundTrip&&<small>Return: {[...o.route].reverse().join(' → ')}</small>}</p><p className="planner-caption">{shortDate(q.depart)}{q.roundTrip?` – ${shortDate(q.returnDate)} · ${nights} nights`:''} · {duration(o.minutes)} outbound<br/>{o.price===cheapest?'Lowest sample price':`${money(o.price-cheapest)} above the lowest suitable sample fare`}</p>
 <section><h3>Available on this trip</h3>{benefits.account?<><div className="offer-membership"><TierBadge account={benefits.account} day={q.depart}/></div><p className="planner-caption">Membership benefits on {benefits.scope}{q.roundTrip?' and the return legs':''}. Other operators can have different rules.</p>{benefits.included.length>0&&<PolicyPerks perks={benefits.included}/>} {benefits.conditional.length>0&&<><h4 className="policy-heading">Conditions & extra steps</h4><PolicyPerks perks={benefits.conditional}/></>}<PolicyLinks perks={benefits.perks}/><p className="planner-caption">These benefits use your {benefits.tier} membership. Choosing where to earn miles below does not transfer this tier. Confirm membership recognition with the airline if using a different crediting program.</p></>:<p className="planner-caption">No current tier policy matches these travel dates and operators in this demo. Your fare details are below.</p>}
 <details className="fare-assumptions"><summary>Fare details & operating airlines</summary><p>{offerOperators(o).map(l=>`${l.from}–${l.to}: ${l.carrier}`).join(' · ')}{q.roundTrip?' · same operators assumed on return':''}.</p><p>{o.bags} checked bags included in this fare scenario. {o.lounge?'Business scenario assumes lounge access for the international premium-cabin leg; confirm specific lounges and connection eligibility.':'This fare scenario does not include lounge access.'} Fare inclusions are illustrative; the policy-backed membership benefits above are evaluated separately.</p></details></section>
 <section><h3>Make this trip count</h3>{eligibleAccounts.length?<><label className="field">Credit this scenario to<select aria-label="Scenario credit program" value={accountId} onChange={e=>setAccountId(e.target.value)}>{eligibleAccounts.map(a=><option key={a.id} value={a.id}>{programs.find(p=>p.id===a.program)?.name}</option>)}</select></label><p className="planner-caption">Credit goes to one program. Calculations use the fare assumptions below; tier and card bonuses are excluded.</p></>:<p className="planner-caption">No matching account is saved. Add {o.credits.map(c=>programs.find(p=>p.id===c.program)?.name).join(' or ')} from Mileage & status to compare your goal.</p>}
 <div className="scenario-earn"><span>Calculated base earnings</span><strong>+{n(credit.miles*(q.roundTrip?2:1))} {p?.currency??'miles'}</strong><small>{p?.name} · tier/card bonuses excluded</small></div><details className="earning-breakdown"><summary>How we calculated this</summary><p>{q.roundTrip?'Each direction earns the amount below; the return uses the same classes and spend.':'One-way calculation.'}</p><ul>{credit.formula.map(line=><li key={line}>{line}</li>)}</ul><p>{credit.assumptions}</p><a href={credit.source} target="_blank" rel="noopener noreferrer">Airline earning rules ↗</a>{credit.program==='ana'&&<a href={earningSources.premium} target="_blank" rel="noopener noreferrer">Premium Points rules ↗</a>}{credit.program==='ba'&&<a href={earningSources.tier} target="_blank" rel="noopener noreferrer">Tier point rules ↗</a>}</details>{a&&p&&v&&<><div className="scenario-progress"><div><strong>{a.goal==='retain'?'Retain':a.goal==='redeem'?'Save for':'Reach'} {a.goalName}</strong><small>Goal ends {a.end}</small><small>Target: {n(a.target)} {unitFor(a)}</small></div><GrowthBar current={v.current} earned={v.earned} target={a.target} unit={unitFor(a)}/><div className="scenario-three"><span>Current<strong>{n(v.current)}</strong></span><span>This trip<strong>+{n(v.earned)}</strong></span><span>After trip<strong>{n(v.after)}</strong></span></div><p>{n(v.remaining)} {unitFor(a)} remaining</p>{a.goal!=='redeem'&&a.secondTarget>0&&<div className="scenario-secondary"><strong>{p.second}</strong><span>{n(a.second)} → {n(v.secondAfter)} / {n(a.secondTarget)}</span><GrowthBar current={a.second} earned={v.second} target={a.secondTarget} unit={p.second??'points'}/><small>{n(v.secondRemaining)} still needed</small></div>}{v.eligible<v.legs&&<p className="planner-caution">{v.legs-v.eligible} direction(s) fall outside this goal period. Only in-period credit contributes to the goal.</p>}<small className="planner-caption">Starts from your entered balance. Other booked and pending credits are excluded.</small></div>
 <div className="next-benefits"><Sparkle size={21}/><div><strong>{a.rule==='ana-platinum'?(v.met&&!v.alreadyMet?'Both targets reached in this scenario':'Next milestone: Platinum'):a.goal==='redeem'?'Your reward goal':'Your personal target'}</strong><p>{a.rule==='ana-platinum'?'Potential next-tier benefits include eligible lounge access and priority services. Both Premium Points requirements must be met; benefits start only when ANA confirms and activates the tier.':a.goal==='redeem'?'Reaching your savings goal does not guarantee an award seat. Check the reward price and availability with the airline.':'This is your personal target, not a confirmed airline status threshold. No new tier benefits are assigned automatically.'}</p>{benefits.account?.id===a.id&&benefits.policy?.next&&<><PolicyPerks perks={benefits.policy.next.perks}/><PolicyLinks perks={benefits.policy.next.perks}/></>}{a.rule==='ana-platinum'&&<a href="https://www.ana.co.jp/en/jp/amc/premium/overview/premium-point/" target="_blank" rel="noreferrer">Check ANA requirements</a>}</div></div></>}
 </section><a className="primary airline-booking" href={credit.program==='united'?bookingSites.United:o.bookingUrl} target="_blank" rel="noopener noreferrer">Book on {credit.program==='united'?'United':o.carrier}<ArrowRight size={18}/></a><p className="planner-caption">Opens the airline’s official website. Search and confirm the fare there; prices and seats are not reserved.{credit.program==='united'&&o.carrier!=='United'?' Choose a United-issued ticket for this calculation.':''}</p><div className="planner-notice"><Info size={18}/><span>Just exploring<small>Closing this comparison leaves your flights, balances and booked estimates unchanged.</small></span></div><button className="primary" onClick={onClose}>Back to options</button></div></BottomSheet>;
}
