import {useState} from 'react';
import {ArrowRight,ArrowsLeftRight,CheckCircle,CaretRight,SlidersHorizontal,AirplaneTilt,Info,Suitcase,Armchair,Sparkle} from '@phosphor-icons/react';
import {BottomSheet,KeyboardInput,MobileScroll,useKeyboard} from './mobile';
import {useApp,CarrierBadge} from './Prototype';
import {airports,duration} from './domain';
import {accountsFor,programs,type LoyaltyAccount} from './loyalty';
import {airportInput,benefitsFor,cabins,money,offersFor,projectionFor,rankOffers,validateQuery,type PlannerQuery,type Priority,type Offer} from './planner';
import './planner.css';
const n=(v:number)=>v.toLocaleString('en-US');
const shortDate=(day:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(day));
const unitFor=(a:LoyaltyAccount)=>{const p=programs.find(p=>p.id===a.program)!;return a.goal==='redeem'?(p.currency??'miles'):p.unit;};

export default function MileagePlanner({initialDestination=''}:{initialDestination?:string}){
 const app=useApp(),keyboard=useKeyboard(),accounts=app.state.empty?[]:accountsFor(app.state);
 const [from,setFrom]=useState(app.state.homeBases?.[0]??'PIT'),[to,setTo]=useState(initialDestination),[depart,setDepart]=useState('2026-10-07'),[returnDate,setReturnDate]=useState('2026-10-17'),[roundTrip,setRoundTrip]=useState(true);
 const [query,setQuery]=useState<PlannerQuery|null>(null),[editing,setEditing]=useState(false),[cabin,setCabin]=useState<PlannerQuery['cabin']>('Economy'),[searchCabin,setSearchCabin]=useState<PlannerQuery['cabin']>('Economy'),[priority,setPriority]=useState<Priority>('price'),[nonstop,setNonstop]=useState(false),[goalId,setGoalId]=useState(app.state.pinnedProgram??accounts[0]?.id??''),[error,setError]=useState(''),[selected,setSelected]=useState<Offer|null>(null);
 const goal=accounts.find(a=>a.id===goalId),q=query?{...query,cabin,nonstop}:null,offers=q?offersFor(q):[],ranked=q?rankOffers(offers,q,priority,goal,accounts):[],cheapest=offers.length?Math.min(...offers.map(o=>o.price)):0;
 const search=()=>{keyboard.hide();const candidate={from:airportInput(from),to:airportInput(to),depart,returnDate,roundTrip,cabin:searchCabin,nonstop};const issue=validateQuery(candidate);if(issue){setError(issue);return;}setError('');setQuery(candidate);setCabin(searchCabin);setEditing(false);};
 const editSearch=()=>{if(q){setFrom(q.from);setTo(q.to);setDepart(q.depart);setReturnDate(q.returnDate);setRoundTrip(q.roundTrip);setSearchCabin(q.cabin);}setError('');setEditing(true);};
 const form=<div className="planner-form"><div className="choice-segments" aria-label="Journey type">{[true,false].map(v=><button key={String(v)} type="button" aria-pressed={roundTrip===v} onClick={()=>{keyboard.hide();setRoundTrip(v);}}>{v?'Round trip':'One way'}</button>)}</div><div className="planner-route-fields"><label className="field">From<KeyboardInput aria-label="Departure city or airport" value={from} onChange={e=>setFrom(e.target.value)} placeholder="Pittsburgh or PIT"/></label><ArrowsLeftRight size={20}/><label className="field">To<KeyboardInput aria-label="Destination city or airport" value={to} onChange={e=>setTo(e.target.value)} placeholder="Tokyo or HND"/></label></div><div className="planner-quick" aria-label="Sample destinations">{['Tokyo','London','Chicago'].map(city=><button onClick={()=>{keyboard.hide();setTo(city);}} key={city}>{city}</button>)}</div><div className="date-pair"><label className="field">Departure date<KeyboardInput type="date" aria-label="Departure date" value={depart} onChange={e=>setDepart(e.target.value)}/></label>{roundTrip&&<label className="field">Return date<KeyboardInput type="date" aria-label="Return date" value={returnDate} onChange={e=>setReturnDate(e.target.value)}/></label>}</div><label className="field">Cabin<select aria-label="Search cabin" value={searchCabin} onChange={e=>setSearchCabin(e.target.value as typeof cabin)}>{cabins.map(c=><option key={c}>{c}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" onClick={search}>Compare flights<ArrowRight size={19}/></button><p className="planner-caption">Sample routes from Pittsburgh or San Francisco to Tokyo, London and Chicago. One adult · cash fares in USD.</p>{editing&&<button className="text-button" onClick={()=>{keyboard.hide();setEditing(false);setError('');}}>Cancel changes</button>}</div>;
 return <><MobileScroll className="planner-scroll"><main className="planner-page">
 {!q?<><span className="planner-eyebrow"><Sparkle size={15}/> A LITTLE MORE FROM EVERY FLIGHT</span><h1>Make your next<br/>flight count.</h1><p className="planner-intro">Compare the cost, the perks, and the progress toward your next goal.</p><div className="planner-notice"><Info size={18}/><span>Try a planning scenario<small>Illustrative fares and earnings. Nothing is booked or added to your balance.</small></span></div>{form}</>:<>
 <button className="planner-search-summary" onClick={editSearch} aria-label="Edit trip search"><span><small>{q.roundTrip?'ROUND TRIP':'ONE WAY'} · 1 ADULT</small><strong>{q.from}<ArrowRight size={20}/>{airports[q.to].city}</strong><small>{shortDate(q.depart)}{q.roundTrip?` – ${shortDate(q.returnDate)}`:''} · {q.depart.slice(0,4)}{q.roundTrip&&q.depart.slice(0,4)!==q.returnDate.slice(0,4)?` / ${q.returnDate.slice(0,4)}`:''}</small></span><SlidersHorizontal size={23}/></button>
 <div className="planner-cabins" role="group" aria-label="Cabin">{cabins.map(c=><button aria-pressed={cabin===c} key={c} onClick={()=>setCabin(c)}>{c==='Premium economy'?'Premium':c}</button>)}</div>
 <div className="planner-filters"><label>Prioritize<select aria-label="Prioritize" value={priority} onChange={e=>setPriority(e.target.value as Priority)}><option value="price">Lowest cost</option><option value="goal" disabled={!accounts.length}>My goal</option><option value="benefits">Trip benefits</option></select></label><button role="switch" aria-checked={nonstop} className={nonstop?'nonstop active':'nonstop'} onClick={()=>setNonstop(!nonstop)}>Nonstop{nonstop&&<CheckCircle size={15}/>}</button></div>
 {accounts.length>0&&<label className="planner-goal-select">Your goal<select aria-label="Comparison goal" value={goalId} onChange={e=>setGoalId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{programs.find(p=>p.id===a.program)?.carrier} · {a.goalName}</option>)}</select></label>}
 <div className="planner-results-heading"><h2>{ranked.length?`${ranked.length} options to explore`:'No sample options'}</h2><span>Sample fares</span></div><p className="planner-caption">{q.roundTrip?'Return':'One-way'} total · USD / adult · taxes & listed bags included. Sample fares and earnings.</p>
 {!ranked.length?<div className="planner-empty"><AirplaneTilt size={36}/><h3>Let’s try another scenario.</h3><p>{nonstop?'No nonstop sample matches these choices.':cabin!=='Economy'&&q.to==='ORD'?'Chicago currently has Economy samples only.':'This route is not in our sample library yet.'}</p>{nonstop&&<button className="secondary" onClick={()=>setNonstop(false)}>Include connections</button>}<button className="secondary" onClick={()=>{setFrom('PIT');setTo('Tokyo');setCabin('Economy');setNonstop(false);setQuery({...q,from:'PIT',to:'HND',cabin:'Economy',nonstop:false});}}>Try Pittsburgh to Tokyo</button><button className="text-button" onClick={editSearch}>Change search</button></div>:ranked.map((o,i)=>{
 const v=projectionFor(goal,o,q),benefits=benefitsFor(o,q,accounts),name=programs.find(p=>p.id===goal?.program)?.name;
 const reason=priority==='goal'?(v?.improvement?`${n(v.earned)} ${goal?unitFor(goal):''} toward your goal${v.met?' · target reached in this scenario':''}`:v?'No additional progress in this goal period':'No modeled credit to your selected program'):priority==='benefits'?`${benefits.perks.length} modeled benefits on this journey`:`${o.price===cheapest?'Lowest sample price':`${money(o.price-cheapest)} more than the lowest price`}`;
 return <button className={`planner-offer ${i===0?'recommended':''}`} key={o.id} onClick={()=>setSelected(o)} aria-label={`Explore ${o.carrier} option`}>
 {i===0&&<span className="offer-recommendation"><Sparkle size={14}/>{priority==='goal'&&v?.improvement?'Strongest goal progress':priority==='benefits'?'Most modeled benefits':'Lowest sample price'}</span>}
 <div className="offer-title"><CarrierBadge carrier={o.carrier}/><span><strong>{o.carrier}</strong><small>{o.route.length===2?'Nonstop':`1 stop · ${o.route[1]}`} · {duration(o.minutes)}</small></span><b>{money(o.price)}<small>{q.roundTrip?'round trip':'one way'}</small></b></div>{!(priority==='price'&&i===0)&&<p className="offer-reason">{reason}</p>}
 <div className="offer-credit"><span>{v?`Credit to ${name}`:'Other credit options'}<strong>{v?`+${n(v.miles)} ${programs.find(p=>p.id===goal?.program)?.currency??'miles'}`:'See program & estimate'}</strong></span><CaretRight size={19}/></div><div className="offer-perks"><Suitcase size={14}/>{o.bags} {o.bags===1?'bag':'bags'}{benefits.perks.some(p=>p.label==='Priority check-in')&&<><CheckCircle size={14}/>Priority</>}{o.lounge&&<><Armchair size={14}/>Lounge</>}</div></button>;
 })}
 <p className="planner-caption planner-bottom-note">Outbound journey times shown. Your accounts stay unchanged while you compare. Confirm actual earnings and benefits with the airline.</p></>}
 </main></MobileScroll>
 <BottomSheet open={editing} onOpenChange={v=>{if(!v)keyboard.hide();setEditing(v);}} title="Edit your trip" snap={.94}>{form}</BottomSheet>
 {selected&&q&&<OfferDetails key={selected.id} offer={selected} query={q} accounts={accounts} preferred={goalId} cheapest={cheapest} onClose={()=>setSelected(null)}/>}
 </>;
}
function OfferDetails({offer:o,query:q,accounts,preferred,cheapest,onClose}:{offer:Offer;query:PlannerQuery;accounts:LoyaltyAccount[];preferred:string;cheapest:number;onClose:()=>void}){
 const eligibleAccounts=accounts.filter(a=>o.credits.some(c=>c.program===a.program));
 const [accountId,setAccountId]=useState(eligibleAccounts.find(a=>a.id===preferred)?.id??eligibleAccounts[0]?.id??'');
 const a=eligibleAccounts.find(a=>a.id===accountId),p=programs.find(p=>p.id===a?.program),v=projectionFor(a,o,q),benefits=benefitsFor(o,q,accounts),nights=Math.round((Date.parse(q.returnDate)-Date.parse(q.depart))/86400000);
 return <BottomSheet open onOpenChange={v=>!v&&onClose()} title="Your flight, your benefits" description="Planning scenario · sample fares and earnings" snap={.94}><div className="planner-detail"><div className="offer-title"><CarrierBadge carrier={o.carrier}/><span><strong>{o.carrier}</strong><small>{o.cabin} · {q.roundTrip?'Round trip':'One way'}</small></span><b>{money(o.price)}<small>USD total</small></b></div><p className="detail-route">{o.route.join(' → ')}{q.roundTrip&&<small>Return: {[...o.route].reverse().join(' → ')}</small>}</p><p className="planner-caption">{shortDate(q.depart)}{q.roundTrip?` – ${shortDate(q.returnDate)} · ${nights} nights`:''} · {duration(o.minutes)} outbound<br/>{o.price===cheapest?'Lowest sample price':`${money(o.price-cheapest)} above the lowest suitable sample fare`}</p>
 <section><h3>Enjoy on this journey</h3><p className="planner-caption">Modeled fare benefits{benefits.tierModeled?` + sample ${benefits.tier} membership`:''}.</p><ul className="benefit-list">{benefits.perks.map(perk=><li key={perk.label}><CheckCircle size={19}/><span><strong>{perk.label}</strong><small>{perk.reason}</small></span></li>)}</ul>{!o.lounge&&<p className="planner-caption">Lounge access is not included in this sample fare.</p>}{benefits.unknown&&<p className="planner-caption">Status benefits are not modeled for your entered tier or these dates. Check eligibility with the airline.</p>}</section>
 <section><h3>Make this trip count</h3>{eligibleAccounts.length?<><label className="field">Credit this scenario to<select aria-label="Scenario credit program" value={accountId} onChange={e=>setAccountId(e.target.value)}>{eligibleAccounts.map(a=><option key={a.id} value={a.id}>{programs.find(p=>p.id===a.program)?.name}</option>)}</select></label><p className="planner-caption">One program receives this flight credit. These are scenario values, not a fare-class calculation.</p></>:<p className="planner-caption">No matching account is saved. Add {o.credits.map(c=>programs.find(p=>p.id===c.program)?.name).join(' or ')} from Mileage & status to compare your goal.</p>}
 {a&&p&&v&&<><div className="scenario-earn"><span>Estimated earnings</span><strong>+{n(v.miles)} {p.currency??'miles'}</strong><small>Redeemable balance · separate from status</small></div><div className="scenario-progress"><div><strong>{a.goal==='retain'?'Retain':a.goal==='redeem'?'Save for':'Reach'} {a.goalName}</strong><small>Goal ends {a.end}</small></div><progress aria-label="Goal after proposed trip" value={Math.min(a.target,v.after)} max={a.target}/><div className="scenario-three"><span>Current<strong>{n(v.current)}</strong></span><span>This trip<strong>+{n(v.earned)}</strong></span><span>After trip<strong>{n(v.after)}</strong></span></div><p>{n(v.remaining)} {unitFor(a)} remaining</p>{a.goal!=='redeem'&&a.secondTarget>0&&<div className="scenario-secondary"><strong>{p.second}</strong><span>{n(a.second)} → {n(v.secondAfter)} / {n(a.secondTarget)}</span><small>{n(v.secondRemaining)} still needed</small></div>}{v.eligible<v.legs&&<p className="planner-caution">{v.legs-v.eligible} direction(s) fall outside this goal period. Only in-period credit contributes to the goal.</p>}<small className="planner-caption">Starts from your entered balance. Other booked and pending credits are excluded.</small></div>
 <div className="next-benefits"><Sparkle size={21}/><div><strong>{a.rule==='ana-platinum'?(v.met&&!v.alreadyMet?'Both targets reached in this scenario':'Next milestone: Platinum'):a.goal==='redeem'?'Your reward goal':'Your personal target'}</strong><p>{a.rule==='ana-platinum'?'Potential next-tier benefits include eligible lounge access and priority services. Both Premium Points requirements must be met; benefits start only when ANA confirms and activates the tier.':a.goal==='redeem'?'Reaching your savings goal does not guarantee an award seat. Check the reward price and availability with the airline.':'This is your personal target, not a confirmed airline status threshold. No new tier benefits are assigned automatically.'}</p>{a.rule==='ana-platinum'&&<a href="https://www.ana.co.jp/en/jp/amc/premium/overview/premium-point/" target="_blank" rel="noreferrer">Check ANA requirements</a>}</div></div></>}
 </section><div className="planner-notice"><Info size={18}/><span>Just exploring<small>Closing this comparison leaves your flights, balances and booked estimates unchanged.</small></span></div><button className="primary" onClick={onClose}>Back to options</button></div></BottomSheet>;
}
