import {createContext,useContext,useState,type ReactNode} from 'react';
import {AirplaneTilt,ArrowDown,CaretRight,Export,GlobeHemisphereWest,IdentificationCard,Moon,X} from '@phosphor-icons/react';
import {geoNaturalEarth1,geoPath} from 'd3-geo';
import {feature} from 'topojson-client';
import landTopology from 'world-atlas/land-110m.json';
import {Carousel,MobileScroll,useFlow} from './mobile';
import {useApp,CarrierBadge,screen} from './Prototype';
import {airports,compactDuration,date,duration,filterFlights,milesFromKm,ordered,type Flight,type Trip} from './domain';
import {flightHistogram,passportStats,tripInsights,type Ranking} from './passportStats';
import './passport.css';
const PassportShare=createContext<{records:Flight[];title:string}>({records:[],title:'Flighty Passport'});
const n=(v:number)=>v.toLocaleString('en-US');
const land=feature(landTopology as any,landTopology.objects.land as any);
const projection=geoNaturalEarth1().fitExtent([[6,12],[594,296]],land as any),path=geoPath(projection);
export function PassportMap({flights}:{flights:Flight[]}){
 const fs=flights.filter(f=>f.status==='flown'),codes=[...new Set(fs.flatMap(f=>[f.from,f.to]))];
 return <svg className="passport-world-map" viewBox="0 0 600 310" role="img" aria-label={`World map of ${fs.length} recorded flights`}><path d={path(land as any)??''} fill="#6a20ef"/>{[...new Map(fs.map(f=>[f.from+'-'+f.to,f])).values()].map(f=><path key={f.id} d={path({type:'LineString',coordinates:[[airports[f.from].lon,airports[f.from].lat],[airports[f.to].lon,airports[f.to].lat]]})??''} fill="none" stroke="#f4eaff" strokeWidth="1.8" opacity=".9"/>)}{codes.map(code=>{const a=airports[code],xy=projection([a.lon,a.lat])!;return <circle key={code} cx={xy[0]} cy={xy[1]} r="3.3" fill="#edb749" stroke="white" strokeWidth="1.4"><title>{code} · {a.city}</title></circle>;})}</svg>;
}
export function PassportHero({flights,title,preview=false}:{flights:Flight[];title:string;preview?:boolean}){
 const s=passportStats(flights);
 return <section className={`passport-book ${preview?'preview':''}`} aria-label={title}><div className="passport-map-panel"><PassportMap flights={flights}/><div className="passport-flags">{s.countries.map(c=><img key={c.key} src={`/assets/flags/${c.key}.png`} alt={c.name} draggable={false}/>)}</div></div><div className="passport-book-copy"><div className="section-heading"><h2>{title}</h2><AirplaneTilt size={26} weight="fill"/></div><p className="passport-caption"><IdentificationCard size={14}/> PASSPORT · PASS · PASAPORTE</p><div className="passport-book-grid"><div><span>FLIGHTS</span><strong>{s.count}</strong></div><div><span>FLIGHT DISTANCE</span><strong>{s.estimated?'≈':''}{n(s.km)}<small> km</small></strong></div><div><span>FLIGHT TIME{s.missing?' · PARTIAL':''}</span><strong>{compactDuration(s.minutes)}</strong></div><div className="passport-book-pair"><div><span>AIRPORTS</span><strong>{s.airports}</strong></div><div><span>AIRLINES</span><strong>{s.carriers}</strong></div></div></div><div className="passport-book-stamp">FLIGHTY · YOUR JOURNEYS, TOGETHER<br/>REFERENCE & SAMPLE FLIGHTS</div></div></section>;
}
function summaryText(fs:Flight[],title:string){const s=passportStats(fs);return `${title}\n${s.count} completed flights · ${s.estimated?'Approx. ':''}${n(s.km)} km\n${duration(s.minutes)}${s.missing?` (time available for ${s.knownTimeCount}/${s.count} flights)`:''}\n${s.airports} airports · ${s.carriers} airlines · ${s.countries.length} countries & territories\nReference and sample data; distances are not loyalty credits.`;}
export function downloadSummary(fs:Flight[],title:string){const url=URL.createObjectURL(new Blob([summaryText(fs,title)],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='flighty-passport-summary.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PassportDetailHeader({tripId=''}:{tripId?:string}){
 const app=useApp(),flow=useFlow(),trip=app.state.trips.find(t=>t.id===tripId),fs=trip?ordered(trip.flightIds,app.records):filterFlights(app.year,'All airlines',app.state.empty?[]:app.records);
 return <div className="passport-detail-header"><div className="passport-detail-toolbar"><button aria-label="Close Flighty Passport" onClick={()=>flow.pop()}><X size={27}/></button><strong>{trip?'Trip Passport':'Flighty Passport'}</strong><button aria-label="Download Passport summary" onClick={()=>downloadSummary(fs,trip?.title??app.year)}><Export size={24}/></button></div>{!trip&&<Carousel className="passport-periods" ariaLabel="Flighty Passport period"><div>{['All time','2026','2025','2024','2023','2022'].map(y=><button key={y} aria-pressed={app.year===y} onClick={()=>app.setYear(y)}>{y==='All time'?'ALL-TIME':y}</button>)}</div></Carousel>}</div>;
}
function Section({title,children}:{title:string;children:ReactNode}){const data=useContext(PassportShare);const share=()=>{const s=passportStats(data.records);const detail=title==='Flights'?`${s.count} flights: ${s.domestic} domestic, ${s.international} international, ${s.longHaul} long haul`:title==='Flight Distance'?`${n(s.km)} km · ${n(milesFromKm(s.km))} mi · ${n(s.averageKm)} km average`:title==='Flight Time'?`${duration(s.minutes)} · time recorded for ${s.knownTimeCount}/${s.count} flights`:title==='Countries & Territories'?s.countries.map(c=>`${c.name}: ${c.count} flights`).join('\n'):(title==='Top Airlines'?s.airlines:title==='Top Routes'?s.routes:s.airportVisits).map(r=>`${r.key}: ${r.count}${title==='Top Visited Airports'?' visits':' flights'}`).join('\n');const url=URL.createObjectURL(new Blob([`${data.title} · ${title}\n${detail}\nReference and sample data; some records are incomplete or estimated.`],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='flighty-'+title.toLowerCase().replaceAll(' ','-')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};return <section className="passport-stat-section"><div className="passport-section-heading"><h2>{title}</h2>{title!=='About these totals'&&<button aria-label={`Share ${title}`} onClick={share}><Export size={15}/>Share</button>}</div>{children}</section>;}
function Extremes({label,flights,metric}:{label:string;flights:Flight[];metric:'distance'|'time'}){
 const [more,setMore]=useState(false),flow=useFlow();return <div className="passport-extremes"><h3>{label}</h3>{flights.slice(0,more?5:1).map(f=><button className="passport-record" key={f.id} onClick={()=>flow.push(screen('flight',f.id))}><CarrierBadge carrier={f.carrier}/><span><strong>{airports[f.from].city} → {airports[f.to].city}</strong><small>{f.number} · {date(f,true)}</small></span><b>{metric==='distance'?`${f.distanceEstimated?'≈':''}${n(f.km)} km`:duration(f.minutes)}</b></button>)}{flights.length>1&&<button className="passport-show-more" aria-expanded={more} onClick={()=>setMore(!more)}>{more?'Show Less':'Show More'}</button>}</div>;
}
function Rankings({title,rows,unit,hasDistance=false,airline=false}:{title:string;rows:Ranking[];unit:string;hasDistance?:boolean;airline?:boolean}){
 const [mode,setMode]=useState<'Flights'|'Distance'>('Flights'),[more,setMore]=useState(false),[active,setActive]=useState<string|null>(null),flow=useFlow();const sorted=[...rows].sort((a,b)=>(mode==='Distance'?b.km-a.km:b.count-a.count)||a.key.localeCompare(b.key)),max=Math.max(1,...sorted.map(r=>mode==='Distance'?r.km:r.count));
 return <Section title={title}><p className="passport-big-number">{rows.length}<span> total {unit}</span></p>{hasDistance&&<div className="passport-segments" aria-label={`${title} metric`}>{(['Flights','Distance'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div>}{title==='Top Visited Airports'&&<p className="passport-footnote">Connections under 8 hours count as one visit when both times are known.</p>}<div className={`passport-ranking ${airline?'airline-ranking':''}`}>{sorted.slice(0,more?sorted.length:8).map(r=><div key={r.key}><button aria-label={`${r.key}: ${mode==='Distance'?n(r.km)+' km':r.count+' flights'}`} className="passport-bar-row" aria-expanded={active===r.key} onClick={()=>setActive(active===r.key?null:r.key)}>{airline?<CarrierBadge carrier={r.key}/>:<span className="rank-label">{r.key}</span>}<span className="rank-track"><span style={{width:`${Math.max(1,(mode==='Distance'?r.km:r.count)/max*100)}%`}}/></span><b>{mode==='Distance'?`${r.estimated?'≈':''}${n(r.km)}`:r.count}</b></button>{active===r.key&&<div className="rank-records"><p>{r.key}{mode==='Distance'?' · kilometers':''}</p>{r.flights.map(f=><button key={f.id} onClick={()=>flow.push(screen('flight',f.id))}>{f.number} · {f.from} → {f.to}<CaretRight size={15}/></button>)}</div>}</div>)}</div>{sorted.length>8&&<button className="passport-show-more" onClick={()=>setMore(!more)} aria-expanded={more}>{more?'Show Less':'Show More'}</button>}{mode==='Distance'&&<p className="passport-footnote">Kilometers from individual records. ≈ marks estimated distances; the reported 2023 total has no complete per-flight breakdown.</p>}</Section>;
}
export function TripSummaryCard({trip,flights}:{trip:Trip;flights:Flight[]}){
 const s=tripInsights(flights),flow=useFlow();return <button className="trip-passport-card" aria-label={`Open ${trip.title} trip summary`} onClick={()=>flow.push(screen('trip-passport',trip.id))}><div className="section-heading"><span><IdentificationCard size={18}/> YOUR TRIP PASSPORT</span><CaretRight size={20}/></div><div className="trip-summary-grid"><div><strong>{s.days}</strong><span>calendar days</span></div><div><strong>{s.count}</strong><span>flights taken</span></div><div><strong>{s.estimated?'≈':''}{n(s.km)}</strong><span>kilometers flown</span></div><div><strong>{duration(s.minutes)}</strong><span>{s.missing?'recorded time · partial':'flight time'}</span></div></div><p><GlobeHemisphereWest size={22}/><span><b>{s.earthPercent.toFixed(1)}% around Earth</b><small>{s.airports} airports · {s.carriers} {s.carriers===1?'airline':'airlines'} · {s.countries.length} {s.countries.length===1?'country / territory':'countries & territories'}</small></span></p>{s.planned+s.canceled>0&&<small>{s.planned} planned · {s.canceled} canceled · excluded from flown totals</small>}<span className="trip-summary-link">Explore your trip stats<CaretRight size={15}/></span></button>;
}
export default function PassportDetails({tripId=''}:{tripId?:string}){
 const app=useApp(),flow=useFlow(),trip=app.state.trips.find(t=>t.id===tripId),records=trip?ordered(trip.flightIds,app.records):filterFlights(app.year,'All airlines',app.state.empty?[]:app.records),s=passportStats(records),[mode,setMode]=useState<'Year'|'Month'|'Weekday'>('Year'),[countriesMore,setCountriesMore]=useState(false),bars=flightHistogram(records,mode),max=Math.max(1,...bars.map(b=>b.count));const title=trip?`${trip.title.toUpperCase()} TRIP PASSPORT`:app.year==='All time'?'MY FLIGHTY PASSPORT':`${app.year} FLIGHTY PASSPORT`;
 return <PassportShare.Provider value={{records,title}}><MobileScroll className="passport-detail-scroll"><main className="passport-detail-page"><PassportHero flights={records} title={title}/><button className="passport-explore" onClick={e=>{const el=e.currentTarget.closest('.mobile-scroll');if(el)el.scrollTop=el.querySelector('.passport-stat-section')!.getBoundingClientRect().top-el.getBoundingClientRect().top+el.scrollTop;}} aria-label="Explore Passport statistics"><ArrowDown size={27}/></button>{trip&&<div className="trip-insight-note">{tripInsights(records).days} calendar days · {tripInsights(records).surfaceGaps} transfers between different airports. Flown totals exclude planned and canceled flights.</div>}
 <Section title="Flights"><p className="passport-big-number">{s.count}</p><p className="passport-flight-kinds"><b>{s.domestic}</b> domestic<br/><b>{s.international}</b> international<br/><b>{s.longHaul}</b> long haul</p><div className="passport-chart-controls"><span>FLIGHTS PER</span><div className="passport-segments">{(['Year','Month','Weekday'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div></div><div className={`passport-histogram ${mode==='Month'?'months':''}`} role="img" aria-label={bars.map(b=>`${b.label}: ${b.count} flights`).join(', ')}>{bars.map(b=><div key={b.label}><b>{b.count}</b><span style={{height:`${b.count/max*124}px`}}/><small>{b.label}</small></div>)}</div><p className="passport-footnote">Long haul: 4,000 km or more. Dates use each departure airport’s local time.</p></Section>
 <Section title="Flight Distance"><p className="passport-big-number distance-number">{s.estimated?'≈':''}{n(s.km)}<span> km</span></p><p className="passport-subnumber">{n(milesFromKm(s.km))} mi</p><p>Average distance: {n(s.averageKm)} km</p><div className="passport-comparison"><GlobeHemisphereWest size={33} weight="fill"/><span><b>{(s.km/40075).toFixed(1)}×</b> Around Earth</span></div><div className="passport-comparison moon-comparison"><Moon size={33} weight="fill"/><span><b>{(s.km/384400*100).toFixed(1)}%</b> To the Moon</span></div><Extremes label="Shortest flight" flights={s.shortestKm} metric="distance"/><Extremes label="Longest flight" flights={s.longestKm} metric="distance"/></Section>
 <Section title="Flight Time"><p className="passport-big-number time-number">{Math.floor(s.minutes/60)}<span>h </span>{s.minutes%60}<span>m</span></p><div className="passport-time-grid"><div><span>Days</span><strong>{(s.minutes/1440).toFixed(1)}</strong></div><div><span>Weeks</span><strong>{(s.minutes/10080).toFixed(1)}</strong></div><div><span>Avg. Flight Time</span><strong>{duration(s.averageMinutes)}</strong></div><div><span>Time recorded</span><strong>{s.knownTimeCount} / {s.count}<small> flights</small></strong></div></div>{s.missing>0&&<p className="passport-footnote">Partial total. {s.missing} flight duration is unavailable and excluded from the time average.</p>}<Extremes label="Shortest flight" flights={s.shortestTime} metric="time"/><Extremes label="Longest flight" flights={s.longestTime} metric="time"/></Section>
 <Rankings title="Top Visited Airports" rows={s.airportVisits} unit="airports"/><Rankings title="Top Airlines" rows={s.airlines} unit="airlines" airline hasDistance/><Rankings title="Top Routes" rows={s.routes} unit="routes" hasDistance/>
 <Section title="Countries & Territories"><p className="passport-big-number">{s.countries.length}<span> total</span></p>{s.countries.slice(0,countriesMore?s.countries.length:3).map(c=><div className="passport-country" key={c.key}><img src={`/assets/flags/${c.key}.png`} alt=""/><strong>{c.name}</strong><span>{c.count} flights</span></div>)}{s.countries.length>3&&<button className="passport-show-more" onClick={()=>setCountriesMore(!countriesMore)} aria-expanded={countriesMore}>{countriesMore?'Show Less':'Show More'}</button>}<div className="passport-region-grid">{['Asia','North America','Europe','South America','Africa','Oceania'].map(r=><div key={r}><span>{r}</span><strong>{s.countries.filter(c=>c.region===r).length}</strong><small> countries / territories</small></div>)}</div><p className="passport-footnote">Counts airports touched, including connections. Each flight counts once per country or territory; this does not confirm a stay or border entry.</p></Section>
 <Section title="About these totals"><p className="passport-footnote">{s.count} loaded completed flights. The reference screenshots’ 75-flight history is not fully imported. Sample journeys are included in this demo. Distances do not represent loyalty earnings.</p>{s.reported&&<p className="passport-footnote">Includes the reported 2023 total of 23,511 km. CX 882 is 11,662 km; the other three individual distances are estimates. The reported year total is preserved, so individual distance rankings may not sum to it.</p>}<p className="passport-footnote">Flight time is gate-to-gate. Air time and taxi time are not shown as aggregate totals because most records lack that breakdown. Earth comparison uses 40,075 km; Moon comparison uses its average distance of 384,400 km.</p><button className="secondary" onClick={()=>downloadSummary(records,trip?.title??app.year)}><Export size={18}/>Download summary</button>{!trip&&<button className="secondary" onClick={()=>flow.push(screen('matching','','All airlines',app.year))}>View source flights<CaretRight size={18}/></button>}</Section>
 </main></MobileScroll></PassportShare.Provider>;
}
