import {Fragment} from 'react';
import {ArrowRight,AirplaneTakeoff,AirplaneLanding,CaretRight,ArrowsLeftRight} from '@phosphor-icons/react';
import {useFlow} from './mobile';
import {CarrierBadge,screen} from './Prototype';
import {airports,type Flight,type Trip} from './domain';
import {journeyEvent,journeyFor} from './journeyData';
export default function TripJourney({records,trip}:{records:Flight[];trip:Trip}){
 const flow=useFlow(),j=journeyFor(records),first=j.first?journeyEvent(j.first,'departure'):null,last=j.last?journeyEvent(j.last,'arrival'):null;
 return <section className="passport-stat-section journey-section"><div className="passport-section-heading"><h2>Your journey</h2><span>{j.flights.length} flights</span></div><p className="journey-intro">From the first departure to the final arrival.</p>{first&&last?<><div className="journey-boundaries">{[{label:'First departure',e:first,icon:<AirplaneTakeoff size={21}/>},{label:'Final arrival',e:last,icon:<AirplaneLanding size={21}/>}].map(({label,e,icon})=><div key={label}>{icon}<small>{label}</small><strong>{airports[e.airport].city}</strong><span>{e.day}</span><b>{e.clock}</b></div>)}</div><ol className="journey-legs">{j.flights.map((f,i)=>{const dep=journeyEvent(f,'departure'),arr=journeyEvent(f,'arrival'),gap=j.gaps.find(g=>g.before===f.id);return <Fragment key={f.id}>{gap&&<li className="journey-gap"><ArrowsLeftRight size={18}/><span>{gap.from} → {gap.to}<small>{trip.surface?.[`${gap.from}-${gap.to}`]??'Travel not recorded'} · not a flight</small></span></li>}<li><button className="journey-leg" aria-label={`View ${f.number} journey flight`} onClick={()=>flow.push(screen('flight',f.id))}><div className="journey-leg-top"><CarrierBadge carrier={f.carrier}/><span><strong>{f.number}</strong><small>{f.carrier}</small></span><span className="journey-leg-index">{i+1} / {j.flights.length}</span><CaretRight size={17}/></div><div className="journey-leg-times"><div><strong>{f.from}</strong><span>{dep.day}</span><b>{dep.clock}</b></div><ArrowRight size={18}/><div><strong>{f.to}</strong><span>{arr.day}</span><b>{arr.clock}</b></div></div><small className="journey-time-label">{dep.label} · each airport’s local time</small></button></li></Fragment>;})}</ol></>:<p className="passport-footnote">No active flights in this trip.</p>}{j.canceled>0&&<p className="passport-footnote">{j.canceled} canceled {j.canceled===1?'flight':'flights'} excluded from this timeline. Original records remain in the trip.</p>}<p className="passport-footnote">Departure and arrival times are shown when recorded. Missing times and transfers remain explicit.</p></section>;
}
