import {useState} from 'react';
import {CaretRight,Plus,MagnifyingGlass,ArrowCounterClockwise,House} from '@phosphor-icons/react';
import {BottomSheet,KeyboardInput,useFlow,useKeyboard} from './mobile';
import {useApp,screen,PastFlightRow} from './Prototype';
import {airports,candidates,ordered,range,tripRoute,tripDate,undo,type Flight} from './domain';
import TripThumbnail from './TripThumbnail';
export default function TripsList({flights,dense}:{flights:Flight[];dense:boolean}){
 const app=useApp(),flow=useFlow(),keyboard=useKeyboard(),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[homeOpen,setHomeOpen]=useState(false),[bases,setBases]=useState(app.state.homeBases??['PIT']);
 const ids=new Set(flights.map(f=>f.id)),all=app.state.empty?[]:[...candidates(app.state).map(t=>({...t,review:true})),...app.state.trips.map(t=>({...t,review:false}))].filter(t=>t.flightIds.some(id=>ids.has(id))).sort((a,b)=>tripDate(b,app.records).localeCompare(tripDate(a,app.records))),covered=new Set(all.flatMap(t=>t.flightIds));
 const matching=(s:string)=>s.toLowerCase().includes(query.trim().toLowerCase());const groups=all.filter(t=>(category==='All'||t.category===category)&&matching([t.title,t.note,range(t,app.records),...ordered(t.flightIds,app.records).flatMap(f=>[f.from,f.to,airports[f.to].city,f.departure.slice(0,10)])].join(' ')));
 const ungrouped=flights.filter(f=>!covered.has(f.id)&&category==='All'&&matching(`${f.number} ${f.from} ${f.to} ${airports[f.to].city} ${f.departure}`));
 return <><div className="grouped-intro"><p>Your journeys</p><button aria-label="Create a trip" onClick={()=>flow.push(screen('create'))}><Plus size={18}/>Create</button></div><label className="search trip-search"><MagnifyingGlass/><KeyboardInput aria-label="Search trips" placeholder="Destination, date or note" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="trip-filter-row"><div className="choice-segments">{['All','Work','Personal'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><button aria-label="Set home airports" onClick={()=>{keyboard.hide();setBases(app.state.homeBases??['PIT']);setHomeOpen(true);}}><House size={22}/></button></div><p className="group-help">Suggestions stay unsaved until you confirm.{app.year!=='All time'?' Journeys crossing years include all their flights.':''}</p>{app.state.operations.length>0&&<button className="trip-undo" onClick={()=>app.save(undo(app.state),'Last trip edit undone')}><ArrowCounterClockwise/>Undo {app.state.operations.at(-1)?.label.toLowerCase()}</button>}
 {groups.map(t=><button className="past-trip-row" key={t.id} aria-label={`${t.review?'Review trip':'Open trip'}: ${t.title}`} onClick={()=>flow.push(screen(t.review?'review':'trip',t.id))}><TripThumbnail trip={t} records={app.records}/><span className="past-trip-copy"><span className="section-heading"><strong>{t.title}</strong>{t.review?<span className="badge">Review</span>:t.category&&<span className="trip-category">{t.category}</span>}</span><small>{range(t,app.records)}</small><span className="trip-route-label">{t.flightIds.filter(id=>app.records.find(f=>f.id===id)?.status==='flown').length} flights · {tripRoute(ordered(t.flightIds,app.records))}</span>{t.note&&<small className="trip-note-preview">{t.note}</small>}{t.reason&&<small>{t.reason.includes('transfer')?'Includes an unrecorded transfer':'Suggested from your flight history'}</small>}</span><CaretRight size={17}/></button>)}
 {!!ungrouped.length&&<><div className="history-year"><strong>Ungrouped flights</strong><span>{ungrouped.length}</span></div>{ungrouped.map(f=><PastFlightRow key={f.id} flight={f} dense={dense}/>)}</>}{!groups.length&&!ungrouped.length&&<div className="empty"><h2>{query?'No matching trips':'No trips in this view'}</h2><p>Try another year, destination or category.</p>{(query||category!=='All')&&<button className="text-button" onClick={()=>{setQuery('');setCategory('All');}}>Clear filters</button>}</div>}
 <BottomSheet open={homeOpen} onOpenChange={setHomeOpen} title="Your home airports" description="Returning to a home airport ends a suggested trip. Choose more than one if you live between cities." snap={.8}>{Object.values(airports).map(a=><button key={a.code} className={`choice-row ${bases.includes(a.code)?'selected':''}`} aria-pressed={bases.includes(a.code)} onClick={()=>setBases(v=>v.includes(a.code)?v.filter(x=>x!==a.code):[...v,a.code])}>{a.code} · {a.city}</button>)}<button className="primary" disabled={!bases.length} onClick={()=>{if(app.save({...app.state,homeBases:bases},'Home airports saved'))setHomeOpen(false);}}>Save home airports</button><button className="text-button" onClick={()=>setHomeOpen(false)}>Cancel</button></BottomSheet></>;
}
