// Device-local journal. No questions or outcome notes are sent to a server.
export const JOURNAL_KEY='ask-reading-history-v1';
export const questionKey=q=>q.trim().toLocaleLowerCase().replace(/\s+/g,'');
export function validEntry(r){
 return !!r&&typeof r.id==='string'&&typeof r.question==='string'&&r.question.length<=300&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&/^\d{2}:\d{2}$/.test(r.clock)&&typeof r.timeZone==='string'&&Number.isInteger(r.hour)&&r.hour>=0&&r.hour<=23&&Number.isInteger(r.timePalace)&&r.timePalace>=0&&r.timePalace<6&&r.lunar&&Number.isInteger(r.lunar.month)&&r.lunar.month>=1&&r.lunar.month<=12&&Number.isInteger(r.lunar.day)&&r.lunar.day>=1&&r.lunar.day<=30&&typeof r.lunar.text==='string'&&Number.isInteger(r.hourIndex)&&r.hourIndex>=1&&r.hourIndex<=12&&Array.isArray(r.stages)&&r.stages.length===3&&r.stages.every(s=>Number.isInteger(s.start)&&s.start>=0&&s.start<6&&Number.isInteger(s.count)&&s.count>=1&&s.count<=30&&Number.isInteger(s.end)&&s.end>=0&&s.end<6)&&typeof r.category==='string';
}
export function readJournal(storage){
 try{const raw=storage.getItem(JOURNAL_KEY);if(!raw)return{entries:[],error:false};const parsed=JSON.parse(raw);if(parsed.version!==1||!Array.isArray(parsed.entries)||!parsed.entries.every(validEntry))throw new Error('invalid');return{entries:parsed.entries,error:false};}
 catch{return{entries:[],error:true};}
}
export function writeJournal(storage,entries){
 try{if(!entries.every(validEntry))return false;storage.setItem(JOURNAL_KEY,JSON.stringify({version:1,entries}));return true;}catch{return false;}
}
export function recordReading(reading,now=new Date()){
 return {...reading,id:globalThis.crypto?.randomUUID?.()||`${now.getTime()}-${Math.random().toString(36).slice(2)}`,savedAt:now.toISOString(),review:{outcome:'pending',note:'',actualDate:''},ruleVersion:'inclusive-count-v1'};
}
export const timing=[
 ['约一周','Around one week','大安在参考整理中被解释为约一个礼拜左右见进展。','The reference summary associates Great Peace with progress in roughly one week.'],
 ['迟滞，未定','Delayed · no fixed date','留连侧重停滞或反复，不能据此换算一个固定完成日。','Lingering suggests delays or repeated steps; it does not supply a fixed completion date.'],
 ['很快，近期','Soon · near term','速喜侧重消息来得快；“马上”并没有统一的小时数。','Swift Joy suggests news arriving quickly; “soon” has no standardized number of hours.'],
 ['先处理分歧','Resolve friction first','赤口侧重口舌或人为阻碍，没有可核实的固定天数。','Red Mouth concerns friction or disputes; the consulted summary supplies no fixed number of days.'],
 ['约两周','Around two weeks','小吉在参考整理中被解释为约两个礼拜左右见进展。','The reference summary associates Small Fortune with progress in roughly two weeks.'],
 ['无明确应期','No definite timing','空亡侧重落空或条件不足，不能推导出“某天一定发生”或“永远不会发生”。','Emptiness has no definite timing and cannot establish that something will happen on a certain date—or never happen.']
];
export const journalCopy={
 zh:{brand:'速问',history:'记录',historyTitle:'把问过的事，留给时间。',historyIntro:'保存在当前浏览器，可回看原卦、记录实际结果。不跨设备同步；清理浏览器数据会删除记录。',empty:'还没有记录。起课后会自动保存到这里。',open:'回看原卦',delete:'删除',confirmDelete:'删除这条问事记录及复盘？此操作无法撤销。',outcome:'实际情况',outcomes:['待观察','符合','部分符合','不符合','无法判断'],note:'复盘笔记',notePlaceholder:'发生了什么？哪些相符，哪些不符？',actualDate:'事情发生日期（可选）',save:'保存复盘',saved:'已保存',storageError:'浏览器无法保存记录。请允许网站存储；当前结果仍可查看。',corrupt:'历史记录无法读取，原数据未被覆盖。',timing:'传统应期',timingNote:'仅为传统象意，不是期限保证；来自二手课程整理。',timingTitle:'什么时候，会有回应？',timingIntro:'先在问题里说明事项和观察范围，例如“这次面试，两周内会收到回复吗？”起课仍用提问当下的月、日、时。以下是参考整理中的大致说法，不把宫位数字机械换算成日期。',voiceStarting:'正在连接语音服务…请允许麦克风访问。',voiceTimeout:'语音服务没有响应。请用手机系统浏览器打开，或点输入框后使用键盘上的麦克风听写。',voiceHelp:'点“语音输入”开始识别；若不可用，可点输入框，使用手机键盘上的麦克风。',voiceNetwork:'语音服务连接失败。请检查网络，或用手机键盘的听写功能。',voiceLanguage:'语音服务不支持当前语言。请使用键盘听写或直接输入。',voiceReview:'已填入识别文字，请检查后起课。',voiceNoResult:'未收到识别文字。可以重试，或使用手机键盘听写。',voiceFinish:'结束识别',recordLink:'查看记录',back:'返回问事'},
 en:{brand:'Ask',history:'History',historyTitle:'Let time answer, too.',historyIntro:'Saved in this browser so you can revisit the original reading and record what happened. No cross-device sync; clearing browser data removes your history.',empty:'No readings yet. Your next reading will be saved here.',open:'Revisit reading',delete:'Delete',confirmDelete:'Delete this reading and its reflection? This cannot be undone.',outcome:'What happened?',outcomes:['Pending','Matched','Partly matched','Did not match','Unclear'],note:'Reflection notes',notePlaceholder:'What happened? What matched, and what did not?',actualDate:'Date it happened (optional)',save:'Save reflection',saved:'Saved',storageError:'This browser could not save your history. Allow site storage; you can still view the current result.',corrupt:'History could not be read. The original data has not been overwritten.',timing:'Traditional timing',timingNote:'A symbolic association, not a deadline. Based on secondary course summaries.',timingTitle:'When might something happen?',timingIntro:'Name the event and observation window in your question, for example: “Will I hear back about this interview within two weeks?” Count from the moment you ask. These broad associations come from the reference summary; position numbers are not mechanically converted into dates.',voiceStarting:'Connecting to speech recognition… Please allow microphone access.',voiceTimeout:'The speech service did not respond. Open this page in your phone’s system browser, or tap the text field and use keyboard dictation.',voiceHelp:'Tap “Speak your question” to start. If unavailable, tap the text field and use the microphone on your phone’s keyboard.',voiceNetwork:'The speech service could not connect. Check your network or use keyboard dictation.',voiceLanguage:'This speech service does not support the current language. Use keyboard dictation or type instead.',voiceReview:'Your speech is in the question box. Review it before beginning.',voiceNoResult:'No words were received. Try again or use keyboard dictation.',voiceFinish:'Finish listening',recordLink:'View history',back:'Back to your question'}
};
