// Summarized from the public transcript of Ni Haixia's Tian Ji / Liu Ren lesson.
// Examples and the sentence scaffold are editorial adaptations, not quotations.
const copy={
 zh:{title:'如何提问',intro:'把此刻拿不定主意的事，说成一个具体问题。',close:'关闭提问指南',rules:[['一问一事','只问一次行动或一件事，不把感情、工作、财运放在同一问里，也不问一生运势。'],['用起念的时间','有疑问、想问的当下才起算。询问明天的事，也用现在起念的时间，不是明天的时间。'],['不为换结果重算','同一件事不要换个时辰再问，只为了得到更满意的结果。']],formulaTitle:'可以这样写',formula:'我想做「具体的事」，这一次是否顺利？',examplesTitle:'从课程情境改写的例子',examples:[['谈合作','今天去谈这份合作，能顺利推进吗？'],['出行','这次出门拜访，是否顺利？'],['寻物','我遗失的那份文件，这次能找回吗？']],source:'依据《天纪》六壬法片段的公开文稿整理。',video:'课程视频',transcript:'文字稿',done:'明白了'},
 en:{title:'How to ask',intro:'Turn what you are uncertain about now into one specific question.',close:'Close question guide',rules:[['One matter at a time','Ask about one action or situation. Separate unrelated concerns; avoid asking for a lifetime prediction.'],['Use the moment you ask','Use the time the question arises. Even if the event is tomorrow, calculate from the present moment, not tomorrow’s date.'],['Do not recalculate for a nicer result','Do not move to another time and ask the same question again simply to change the sign.']],formulaTitle:'A simple starting point',formula:'I am considering [a specific action]. Will this occasion go smoothly?',examplesTitle:'Examples adapted from the lesson’s situations',examples:[['A meeting','Will today’s discussion about this collaboration go smoothly?'],['A visit','Will this trip to visit someone go smoothly?'],['A lost item','Can I recover the particular document I have misplaced?']],source:'Summarized from public transcripts of the Tian Ji lesson on Liu Ren.',video:'Lesson video',transcript:'Transcript',done:'Got it'}
};
export function questionGuideMarkup(lang){const c=copy[lang]||copy.zh;return `<dialog id="question-guide" aria-labelledby="question-guide-title" aria-describedby="question-guide-intro"><div class="guide-heading"><h2 id="question-guide-title">${c.title}</h2><button type="button" class="guide-close" aria-label="${c.close}" autofocus>×</button></div><p id="question-guide-intro">${c.intro}</p><ol class="guide-rules">${c.rules.map(([title,body])=>`<li><h3>${title}</h3><p>${body}</p></li>`).join('')}</ol><section class="guide-formula"><h3>${c.formulaTitle}</h3><p>${c.formula}</p></section><section class="guide-examples"><h3>${c.examplesTitle}</h3><dl>${c.examples.map(([topic,text])=>`<div><dt>${topic}</dt><dd>${text}</dd></div>`).join('')}</dl></section><p class="guide-source">${c.source}<br><a href="https://www.bilibili.com/video/BV17z4y1e73x/" target="_blank" rel="noopener">${c.video} ↗</a></p><button type="button" class="guide-done">${c.done}</button></dialog>`;}
export function bindQuestionGuide(onOpen=()=>{}){
 const trigger=document.querySelector('#question-help'),dialog=document.querySelector('#question-guide');if(!trigger||!dialog)return;
 trigger.onclick=()=>{onOpen();dialog.showModal();};
 dialog.querySelector('.guide-close').onclick=()=>dialog.close();dialog.querySelector('.guide-done').onclick=()=>dialog.close();
 dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();});
 dialog.addEventListener('close',()=>trigger.isConnected&&trigger.focus());
}
