import {test} from 'node:test';import assert from 'node:assert/strict';
import {seed,candidates,flights,byId,totals,tripDestination,commit,undo} from '../src/domain.ts';
import {sampleAccount,progressFor,validAccount} from '../src/loyalty.ts';
const credit=(over={})=>({accountId:'sample-ana',stage:'estimated',miles:300,points:850,second:0,note:'',updated:'2026-09-15',...over});
test('posted credit never adds twice; pending and booked are independent and period scoped',()=>{const a=sampleAccount(),cs={next:credit(),ch1:credit({stage:'posted',points:2000}),ch2:credit({stage:'pending',points:400,second:100}),ny1:credit({stage:'pending',points:900})};const p=progressFor(a,cs,flights,'2026-09-15');assert.equal(p.projected,43250);assert.equal(p.waiting,400);assert.equal(p.expected,850);assert.equal(p.secondProjected,22100);assert.equal(p.projectedRemaining,6750);assert.equal(p.remaining,8000);});
test('missing and cancelled credits cannot silently increase progress; zero is known',()=>{const a=sampleAccount();const p=progressFor(a,{next:credit({points:null,second:null}),cancel:credit({stage:'pending',points:5000})},flights);assert.equal(p.projected,a.status);assert.equal(p.unknown,true);assert.equal(progressFor(a,{next:credit({points:0,second:0})},flights).unknown,false);});
test('program attribution is independent of flown airline and original totals',()=>{const before=totals(flights),a=sampleAccount();assert.equal(byId.next.carrier,'United');assert.equal(progressFor(a,{next:credit()},flights).expected,850);assert.equal(progressFor({...a,id:'other'},{next:credit()},flights).expected,0);assert.deepEqual(totals(flights),before);});
test('redemption uses redeemable balance and cannot imply status; goals validate',()=>{const a={...sampleAccount(),goal:'redeem',secondTarget:0,target:25000};assert.equal(progressFor(a,{next:credit()},flights).projected,18800);assert.equal(progressFor({...a,end:'2025-12-31'},{},flights,'2026-09-15').expired,true);assert.throws(()=>validAccount({...a,target:-1}));assert.throws(()=>validAccount({...a,balance:NaN}));assert.throws(()=>validAccount({...a,end:'2025-01-01'}));});
test('general grouping handles new open-jaw records, ignores rebooked cancellations and requires confirmation',()=>{const added=[{...byId.jp1,id:'custom-a',departure:'2027-05-03T12:00:00Z',arrival:'2027-05-03T13:35:00Z'},{...byId.jp2,id:'custom-b',departure:'2027-05-03T16:50:00Z',arrival:'2027-05-04T06:10:00Z'},{...byId.jp3,id:'custom-c',departure:'2027-05-14T07:50:00Z',arrival:'2027-05-14T18:10:00Z'},{...byId.jp4,id:'custom-d',departure:'2027-05-14T20:00:00Z',arrival:'2027-05-15T00:50:00Z'},{...byId.jp2,id:'old-booking',status:'canceled',departure:'2027-05-03T16:50:00Z'}];const s={...seed(),addedFlights:added},before=JSON.stringify(s),c=candidates(s).find(c=>c.flightIds.includes('custom-a'));assert.equal(c.flightIds.length,4);assert.equal(c.destination,'HND');assert.match(c.reason,/transfer/);assert.equal(JSON.stringify(s),before);const next=commit(s,[...s.trips,{...c,id:'saved'}],'Trip saved');assert.ok(!candidates(next).some(c=>c.flightIds.includes('custom-a')));assert.deepEqual(undo(next).trips,s.trips);});
test('multiple home airports split returns, independent journeys do not merge across long gaps',()=>{const s={...seed(),homeBases:['PIT','HND']},cs=candidates(s);assert.ok(cs.some(t=>t.flightIds.join(',')==='jp1,jp2'));assert.ok(cs.some(t=>t.flightIds.join(',')==='jp3,jp4'));assert.ok(cs.every(t=>!t.flightIds.includes('next')&&!t.flightIds.includes('cancel')));});
test('date-only contradictions stay reviewable; cross-year totals stay preserved',()=>{const c=candidates(seed());assert.ok(!c.some(t=>t.flightIds.includes('ref23-jl7039')&&t.flightIds.includes('ref23-jl7017')));assert.equal(tripDestination(seed().trips.find(t=>t.id==='newyork')),'JFK');assert.equal(totals(flights).count,15);});

test('redemption forecast respects the deadline without resetting existing miles',()=>{const a={...sampleAccount(),goal:'redeem',secondTarget:0,end:'2026-09-14'};const p=progressFor(a,{next:credit()},flights,'2026-09-15');assert.equal(p.expected,0);assert.equal(p.projected,a.balance);});
