import {test,expect} from '@playwright/test';
test.setTimeout(60000);test.use({viewport:{width:1400,height:1200},launchOptions:{args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']}});
const current=(p:any)=>p.getByTestId('flow-current');
test.beforeEach(async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();});
test('2023 Passport summary and every grouped history tab match the source records',async({page})=>{
 await page.getByRole('navigation').getByRole('button',{name:'Passport',exact:true}).click();await page.getByRole('button',{name:'Expand panel',exact:true}).click();
 await expect(current(page).locator('.passport-summary')).toContainText('23,511');await expect(current(page).locator('.passport-summary')).toContainText('1d 7h');await expect(current(page).locator('.delay-number')).toHaveText('9');
 await current(page).getByRole('button',{name:'All Flight Stats',exact:true}).click();await expect(current(page).locator('.passport-detail-page')).toContainText('30h 46m');await page.getByRole('button',{name:'Close Flighty Passport',exact:true}).click();
 const sort=page.getByRole('region',{name:'Sort past flights'});
 for(const [name,groups] of [['From',['CAN','HKG','LAX','HND']],['To',['HKG','LAX','HND']],['Airline',['Cathay Pacific','Japan Airlines']],['Aircraft',['A330-300','B777-300 ER','B787-8']]] as const){await sort.getByRole('button',{name:new RegExp('^'+name)}).click();expect(await current(page).locator('.history-group').evaluateAll(es=>es.map(e=>e.getAttribute('data-group')))).toEqual(groups);await expect(current(page).locator('.past-flight-row')).toHaveCount(4);}
 await sort.getByRole('button',{name:/^Date/}).click();await current(page).getByRole('button',{name:'Detailed flight list'}).click();await expect(current(page).getByText('N877BF',{exact:true})).toBeVisible();await expect(current(page).getByText('13h 22m',{exact:true})).toBeVisible();
 await current(page).locator('.past-flight-row').first().click();await expect(current(page).locator('.arrival-banner')).toContainText('11,662');await expect(current(page).getByText('4:51 PM',{exact:true}).first()).toBeVisible();
});
test('add flight date/calendar/result flow persists and rejects duplicates',async({page})=>{
 await page.getByRole('button',{name:'Search flights',exact:true}).click();await current(page).getByLabel('Search flight records').fill('UA123');await current(page).getByRole('button',{name:/United 123 Detected/}).click();await current(page).getByRole('button',{name:'Pick from Calendar'}).click();await page.getByRole('button',{name:'Select 2026-09-15',exact:true}).click();
 await expect(current(page).locator('.flight-search-result')).toContainText('London to Newark');await current(page).locator('.flight-search-result').click();await expect(current(page).locator('.flight-search-result')).toBeDisabled();
 await current(page).getByRole('button',{name:'View My Flights'}).click();await expect(current(page).locator('.upcoming-card')).toContainText('UA 123');await page.reload();await expect(current(page).locator('.upcoming-card')).toContainText('UA 123');
});
test('manual past flight contributes to Passport',async({page})=>{
 await page.getByRole('button',{name:'Search flights',exact:true}).click();await current(page).getByRole('button',{name:'Add Manually',exact:true}).click();await current(page).getByLabel('Manual flight number').fill('UA987');await current(page).getByLabel('Manual departure airport').fill('PIT');await current(page).getByLabel('Manual arrival airport').fill('LHR');await current(page).getByLabel('Manual departure date').fill('2024-08-10');await current(page).getByLabel('Manual duration').fill('430');await current(page).getByRole('button',{name:'Add to My Flights'}).click();
 await page.getByRole('navigation').getByRole('button',{name:'Passport',exact:true}).click();await page.getByRole('button',{name:'Expand panel',exact:true}).click();await page.getByRole('region',{name:'Passport year'}).getByRole('button',{name:'2024',exact:true}).click();await expect(current(page).locator('.past-flight-row')).toHaveCount(1);await expect(current(page).locator('.past-flight-row')).toContainText('UA 987');
});
test('Friends introduction, simulated share and Bobo itinerary persist with correct connections',async({page})=>{
 await page.getByRole('navigation').getByRole('button',{name:'Friends',exact:true}).click();await page.getByRole('button',{name:'Expand panel',exact:true}).click();await current(page).getByRole('button',{name:'Add Friend',exact:true}).click();await expect(page.getByRole('heading',{name:'Flighty Friends',exact:true})).toBeVisible();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Add sample friend Bobo'}).click();
 await expect(current(page).locator('.friend-flight')).toHaveCount(5);await expect(current(page).getByText('21h 18m at SAN',{exact:true})).toBeVisible();await expect(current(page).getByText('1h 15m at LAS',{exact:true})).toBeVisible();await current(page).getByRole('button',{name:'Bobo’s profile'}).click();await expect(current(page).getByRole('heading',{name:'Bobo',exact:true})).toBeVisible();await current(page).locator('.friend-flight').first().click();await expect(current(page).locator('.flight-sheet-heading')).toContainText('WN 2373');
 await page.reload();await page.getByRole('navigation').getByRole('button',{name:'Friends',exact:true}).click();await expect(current(page).locator('.friend-flight')).toHaveCount(5);await current(page).getByRole('button',{name:'Today',exact:true}).click();await expect(current(page).getByRole('heading',{name:'No flights today'})).toBeVisible();
});
