import {test} from 'node:test';import assert from 'node:assert/strict';
import {delayTotals,routeHistory,reference2026,reference2023,reference2023Summary,totals,historyGroups,flightMetadata,compactDuration,addPersonalFlight,seed,personalFlights,commit,ordered} from '../src/domain.ts';
import {sampleSearch,parseFlightNumber,parseDepartureDate,friendFlights,connectionMinutes} from '../src/flightCatalog.ts';
import {normalizeFlight} from '../server/flight-api.mjs';
test('2023 reference totals distinguish reported distance from recorded duration',()=>{const t=totals(reference2023);assert.equal(t.count,4);assert.equal(t.km,23511);assert.equal(t.minutes,1846);assert.equal(compactDuration(t.minutes),'1d 7h');assert.equal(t.airports,4);assert.equal(t.carriers,2);assert.equal(t.reported,true);assert.equal(t.estimated,false);assert.equal(reference2023Summary.delayMinutes,9);assert.ok(reference2023.slice(1).every(f=>f.dateOnly&&f.delay===null));assert.equal(reference2023.filter(f=>f.km>=4000).length,2);assert.equal(totals(reference2023.slice(0,2)).estimated,true);});
test('all five history modes preserve flight membership and correct group headings/counts',()=>{const from=historyGroups(reference2023,'From',true);assert.deepEqual(from.map(g=>g.key),['CAN','HKG','LAX','HND']);const to=historyGroups(reference2023,'To',true);assert.deepEqual(to.map(g=>[g.key,g.rows.length]),[['HKG',2],['LAX',1],['HND',1]]);assert.deepEqual(historyGroups(reference2023,'Airline',true).map(g=>[g.label,g.rows.length]),[['Cathay Pacific',2],['Japan Airlines',2]]);assert.deepEqual(historyGroups(reference2023,'Aircraft',true).map(g=>g.rows.length),[1,2,1]);for(const sort of ['Date','From','To','Airline','Aircraft']){const gs=historyGroups(reference2023,sort,true);assert.equal(new Set(gs.flatMap(g=>g.rows.map(f=>f.id))).size,4);assert.deepEqual(historyGroups(reference2023,sort,false).map(g=>g.key),gs.map(g=>g.key).reverse());}assert.deepEqual(historyGroups(reference2023,'Date',false)[0].rows.map(f=>f.number),['CX 882','CX 983','JL 7017','JL 7039']);assert.equal(flightMetadata(reference2023[2]).registration,'N877BF');});
test('search parser validates flight/date and sample lookup does not fabricate unmatched flights',()=>{assert.equal(parseFlightNumber('ua 123').number,'123');assert.equal(parseFlightNumber('blah123'),null);assert.equal(parseDepartureDate('Friday'),'2026-09-18');assert.equal(parseDepartureDate('2026-02-30'),null);assert.equal(sampleSearch('2026-09-15','UA123').length,1);assert.equal(sampleSearch('2026-09-15','UA9999').length,0);});
test('added flights persist through state, reject duplicates and can participate in trips',()=>{const f=sampleSearch('2026-09-15','UA123')[0],s=addPersonalFlight(seed(),f);assert.equal(personalFlights(s).at(-1).id,f.id);assert.throws(()=>addPersonalFlight(s,{...f,id:'duplicate'}));const grouped=commit(s,[...s.trips,{id:'added',title:'Added trip',flightIds:[f.id],note:''}],'Save');assert.equal(ordered([f.id],personalFlights(grouped))[0].number,'UA 123');assert.throws(()=>addPersonalFlight(seed(),{...f,to:f.from}));});
test('Bobo connection times use timezones and never enter personal Passport totals',()=>{assert.equal(connectionMinutes(friendFlights[1],friendFlights[2]),1278);assert.equal(connectionMinutes(friendFlights[3],friendFlights[4]),75);assert.equal(connectionMinutes(friendFlights[0],friendFlights[1]),null);assert.equal(totals(friendFlights).count,0);});
test('provider response normalization uses supported airports, cancels and real timestamp intervals',()=>{const row={airline:{iata:'UA'},flight:{iata:'UA123'},departure:{iata:'LHR',scheduled:'2026-09-15T06:45:00Z'},arrival:{iata:'EWR',scheduled:'2026-09-15T14:23:00Z'},flight_status:'cancelled'};const f=normalizeFlight(row);assert.equal(f.status,'canceled');assert.equal(f.minutes,458);assert.equal(f.source,'live');assert.equal(normalizeFlight({...row,departure:{iata:'ZZZ'}}),null);});

test('CX 882 specifics reconcile total time, distance, delay and route history',()=>{const f=reference2023[0];assert.equal(f.km,11662);assert.equal(f.distanceEstimated,false);assert.equal(f.delay,3);assert.equal((Date.parse(f.arrival)-Date.parse(f.departure))/60000,802);assert.equal(delayTotals(reference2023).minutes,9);assert.equal(delayTotals([f]).minutes,3);assert.equal(delayTotals([...reference2023,reference2026]).minutes,17);const history=routeHistory(f);assert.deepEqual(history.map(r=>r.number),['UA 821','CX 882']);assert.equal(totals(history).km,23324);assert.equal(totals(history).minutes,1629);assert.equal(totals([...reference2023,reference2026]).km,35173);});
