import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1400,height:1200},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:4174/');await page.locator('.earth-view[data-ready=true]').first().waitFor();
await page.waitForTimeout(1400);
const box=await page.locator('.device-screen').boundingBox();if(!box||Math.abs(box.width-393)>1||Math.abs(box.height-852)>1)throw Error('Unexpected scaled screen: '+JSON.stringify(box));
await page.mouse.move(0,0);await page.locator('.device-screen').screenshot({path:'qa/01-home.png'});
console.log('earth',await page.locator('.earth-view').first().getAttribute('data-camera'));
await page.getByRole('button',{name:'Expand panel',exact:true}).click();await page.waitForTimeout(500);
await page.mouse.move(0,0);await page.locator('.device-screen').screenshot({path:'qa/02-home-expanded.png'});
await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Passport',exact:true}).click();await page.waitForTimeout(1200);
await page.mouse.move(0,0);await page.locator('.device-screen').screenshot({path:'qa/03-passport.png'});
await page.getByRole('button',{name:'Expand panel',exact:true}).click();await page.waitForTimeout(500);
await page.mouse.move(0,0);await page.locator('.device-screen').screenshot({path:'qa/04-passport-expanded.png'});
await page.getByRole('group',{name:'Past flights display'}).scrollIntoViewIfNeeded();await page.locator('[data-flow-current=true] .mobile-scroll').evaluate(el=>{const row=el.querySelector('.past-history');el.scrollTop+=row.getBoundingClientRect().top-el.getBoundingClientRect().top;});await page.waitForTimeout(300);
await page.mouse.move(0,0);await page.locator('.device-screen').screenshot({path:'qa/05-past-flights.png'});
await page.getByRole('group',{name:'Past flights display'}).getByRole('button',{name:'Trips',exact:true}).click();await page.waitForTimeout(300);
await page.mouse.move(0,0);await page.locator('.device-screen').screenshot({path:'qa/06-past-trips.png'});
await page.locator('.aircraft-card').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.mouse.move(0,0);await page.locator('.aircraft-card').screenshot({path:'qa/aircraft-card.png'});
console.log('ERRORS',JSON.stringify(errors));await page.goto('http://127.0.0.1:4174/qa/comparison.html');for(const id of ['collapsed','expanded','history','aircraft']){await page.locator('#'+id+' img').first().waitFor();await page.locator('#'+id).screenshot({path:'qa/compare-'+id+'.png'});}await browser.close();
